### ISSUE TITLE
bnd baselining should ignore @HotSpotIntrinsicCandidate annotation

### ISSUE THREAD

**Issue by reschke** [bndtools/bnd#2177] opened 2017-10-19 14:32 UTC
Context: <https://issues.apache.org/jira/browse/JCR-4191>

What happens here is that the maven bundle plugin's baseline target reports an API change after a missing implementation of "hashCode()" was added. Quoting @kwin:

> Only with Java 9 it sees a difference between the old version (leveraging the OOTB java.lang.Object#hashCode() having the annotation in Java 9) and the new version of jackrabbit-webdav (overwriting the hashCode and therefore not having the annotation for intrinsics.

So this is a change in annotations, but these annotations are added by Java, and the author of the code is not in control.

(and yes, the version bump in theory is harmless, but still...)

**Comment by bjhargrave** [comment] 2017-10-19 14:52
It is asking for a micro version increase (1.0.0 => 1.0.1) since you changed the implementation. That seems more than reasonable.

**Comment by bjhargrave** [comment] 2017-10-19 14:53
BTW, I don't think Bnd should have a list of annotations we ignore for baselining. That list will always be out-of-date or incorrect for someone.

**Comment by kwin** [comment] 2017-10-19 14:53
The point is: It only asks about that version increase in Java 9 but not for any other java version. That is IMHO a bug and should be fixed.

**Comment by timothyjward** [comment] 2017-10-19 14:55
> The point is: It only asks about that version increase in Java 9 but not for any other java version. That is IMHO a bug and should be fixed.

I agree - it should be expecting a version increase on every Java version

**Comment by reschke** [comment] 2017-10-19 14:56
> It is asking for a micro version increase (1.0.0 => 1.0.1) since you changed the implementation.

No, I didn't.

Also, why does it ask for a micro version change when run with Java 9, but not when run with Java 8?

**Comment by bjhargrave** [comment] 2017-10-19 15:00
I guess I am confused. Let me see if I understand.

You have some code. When you build with JDK8 and then baseline, no issue.

When you rebuild the code with JDK9 and then baseline, you get the baseline message because JDK9 added an annotation to your method?

I would think that changing the JDK you build with would merit a micro version bump in any case.

**Comment by reschke** [comment] 2017-10-19 15:02
No, the baseline problem is reported even when the code is built with java 8, and then baseline is run with java 9. So the baseline diagnostics defer based on the java version for identical files being inspected.

**Comment by kwin** [comment] 2017-10-19 15:03
It is actually the other way round. The default ``Object.hashCode()`` carries the annotation ``HotSpotIntrinsicCandidate`` with Java 9. Every custom implementation of ``hashCode()`` doesn't (neither in Java 8 nor 9). Since baselining is comparing the default ``Object.hashCode()`` with the custom one the change on the annotation is detected.

**Comment by timothyjward** [comment] 2017-10-19 15:06
In this case it sounds as though the annotation is immaterial - the issue is that the `hashCode()` implementation change isn't being picked up as a micro change (which it should be).

**Comment by reschke** [comment] 2017-10-19 15:08
hm. Do I hear that the micro version should change because of the JRE the bundle is used with? How is the author of the bundle supposed to predict that?

**Comment by kwin** [comment] 2017-10-19 15:09
No, I guess the micro-version should change, because you in fact changed the implementation of ``hashCode()``.

**Comment by bjhargrave** [comment] 2017-10-19 15:10
See 93052f9264a78503837afc37b7c58386978b9498. Perhaps this is the issue when baselining on JDK9?

**Comment by kwin** [comment] 2017-10-19 15:11
I don't think the class is not being found by bnd, because otherwise the annotation change would not have been detected in the first place.

**Comment by timothyjward** [comment] 2017-10-19 15:11
> hm. Do I hear that the micro version should change because of the JRE the bundle is used with? How is the author of the bundle supposed to predict that?

No, the micro version should change because inheriting the default hashCode() method is not the same as having an implementation of hashCode(). This should be detected on every version of Java.

**Comment by bjhargrave** [comment] 2017-10-19 15:13
> hm. Do I hear that the micro version should change because of the JRE the bundle is used with? How is the author of the bundle supposed to predict that?

Not used with. Built with. So if you change the JDK used to build a bundle, you should bump the version of the bundle.

**Comment by reschke** [comment] 2017-10-19 15:15
> Built with. So if you change the JDK used to build a bundle, you should bump the version of the bundle.

The problem happens even if I build with Java 8 and only run the base line check with Java 9.

**Comment by bjhargrave** [comment] 2017-10-19 15:17
> What happens here is that the maven bundle plugin's baseline target reports an API change after a missing implementation of "hashCode()" was added.

So the baseline bundle does not have the overload of hashCode? But the new version does. And you build on JDK8. Then baselining on JDK8 is OK but baselining on JDK9 produces a message.

I think you are caught in a small gap here. Since the overload is new, the baselining depends upon what you compare against: Object from JDK8 or Object from JDK9. 

I think the answer here is don't baseline on JDK9. Baseline on the JDK you build against.

**Comment by kwin** [comment] 2017-10-19 15:19
> I think the answer here is don't baseline on JDK9. Baseline on the JDK you build against.

Even that does not help here, because even building and running baseline with Java 9 mandates the version change, while Java 8 does not.

**Comment by reschke** [comment] 2017-10-19 15:19
> I think the answer here is don't baseline on JDK9. Baseline on the JDK you build against.

In our project, we try to support multiple JDKs for building. Maybe that's a bad idea in the first place, but so far it hasn't been a problem.

**Comment by bjhargrave** [comment] 2017-10-19 15:20
> Even that does not help here, because even building and running baseline with Java 9 mandates the version change, while Java 8 does not.

Changing build JDK requires a version bump anyway. New osgi.ee requirement, new class file versions.

**Comment by bjhargrave** [comment] 2017-10-19 15:21
> In our project, we try to support multiple JDKs for building. Maybe that's a bad idea in the first place, but so far it hasn't been a problem.

That is great. But rebaselining on JDKs other then the build JDK does not seem useful or helpful in any way. Just a longer build.

**Comment by kwin** [comment] 2017-10-19 15:22
> Changing build JDK requires a version bump anyway. New osgi.ee requirement, new class file versions.

Fine with that, but that is not what brings baseline to suggest the minor version change. It suggest the increase just because the method signature(!) has changed. IMHO it should also suggest an increase whenever a method gets overwritten.

**Comment by reschke** [comment] 2017-10-19 15:29
> Changing build JDK requires a version bump anyway. New osgi.ee requirement, new class file versions.

But shouldn't it ask for many more version bumps than this single one?

**Comment by reschke** [comment] 2017-10-19 15:31
> IMHO it should also suggest an increase whenever a method gets overwritten.

Could you elaborate why?

**Comment by bjhargrave** [comment] 2017-10-19 15:33
> Fine with that, but that is not what brings baseline to suggest the minor version change. It suggest the increase just because the method signature(!) has changed. IMHO it should also suggest an increase whenever a method gets overwritten.

If you had rebuilt with JDK9, you would have gotten many more baseline messages requesting version bumps. Like class file version increases. So the hashCode "issue" would just have been one.

**Comment by bjhargrave** [comment] 2017-10-19 15:34
> > IMHO it should also suggest an increase whenever a method gets overwritten.
> 
> Could you elaborate why?

Perhaps a micro bump as long as binary compatibility is maintained.

**Comment by reschke** [comment] 2017-10-19 15:35
> If you had rebuilt with JDK9, you would have gotten many more baseline messages requesting version bumps. Like class file version increases. So the hashCode "issue" would just have been one.

That's not the case. When I build and baseline-check with JDK9 this is the only version change it asks for.

**Comment by timothyjward** [comment] 2017-10-19 15:35
> > IMHO it should also suggest an increase whenever a method gets overwritten.

> Could you elaborate why?

*Any* change should result in _at least_ a micro bump because the version should reflect that the code has changed. This applies regardless of what the change is. Without this you have two different pieces of code claiming to be the same version, even though they are different. Clients need to be able to choose between these things.

**Comment by bjhargrave** [comment] 2017-10-19 15:37
> That's not the case. When I build and baseline-check with JDK9 this is the only version change it asks for.

Did you change the target to 9?

**Comment by reschke** [comment] 2017-10-19 15:38
> Did you change the target to 9?

No. Good point.

**Comment by reschke** [comment] 2017-10-19 15:40
> Any change should result in at least a micro bump because the version should reflect that the code has changed. This applies regardless of what the change is. Without this you have two different pieces of code claiming to be the same version, even though they are different. Clients need to be able to choose between these things.

"any change"? Really? If that's the case, shouldn't the baseline check actually compare the byte code of the method and complain when it changes?

/me confused

**Comment by bjhargrave** [comment] 2017-10-19 16:02
> "any change"? Really? If that's the case, shouldn't the baseline check actually compare the byte code of the method and complain when it changes?

It should look for that. If the bundle includes src code, it compares the source files to avoid compiler diffs like Javac vs. ECJ. Otherwise it compare binaries.

But I don't have much experience with that since I mostly baseline API only jars for OSGi and in Bnd we bump the bundle version for all bundles at each release boundary.

**Comment by reschke** [comment] 2017-10-23 12:02
> >  That's not the case. When I build and baseline-check with JDK9 this is the only version change it asks for.
>
> Did you change the target to 9?

FWIW, when I build jackrabbit-webdav with Java 9, then do the baseline check, I still get exactly *one* "Version increase required" message, so apparently the class file version currently is not considered.

**Comment by reschke** [comment] 2017-10-23 12:04
So, advice appreciated... Should I:

a) just bump up the minor version number (not being convinced it's the right thing, but harmless in practice), or
b) try to drive this discussion to a proper conclusion

?

**Comment by bjhargrave** [comment] 2017-10-23 12:10
> So, advice appreciated... Should I:

If your target is Java 8, you should build and baseline with JDK 8. And don't baseline with JDK 9.

**Comment by reschke** [comment] 2017-10-23 12:11
> If your target is Java 8, you should build and baseline with JDK 8. And don't baseline with JDK 9.

My target is Java 8, but I want to allow building with JDK 9 (and target version 8).

**Comment by bjhargrave** [comment] 2017-10-23 12:38
> My target is Java 8, but I want to allow building with JDK 9 (and target version 8).

OK, but the canonical artifacts from Maven Central will be built with JDK 8, right? So that is the JDK you baseline on. If you want your build to support someone else building the source with JDK 9, you can support that and should probably configure off baselining for JDK 9.

**Comment by reschke** [comment] 2017-10-23 12:43
>  So that is the JDK you baseline on. If you want your build to support someone else building the source with JDK 9, you can support that and should probably configure off baselining for JDK 9.

In which case, if somebody running on JDK 9 made a change, he/she wouldn't get a baseline check and potentially commit a change that would have required a version bump

**Comment by bjhargrave** [comment] 2017-10-23 12:56
Yes, but don't you have a PR builder (like Travis) which will build the contribution on JDK 8 to catch these (and other errors like test failures) before you merge the contribution into the main branch?

**Comment by bjhargrave** [comment] 2017-10-23 12:56
Basically before you accept a commit, you need to make sure it builds in the canonical build env.

**Comment by reschke** [comment] 2017-10-23 12:58
We are on Subversion, and what I'm concerned with are regular committers who commit directly to trunk.

**Comment by bjhargrave** [comment] 2017-10-23 13:01
I guess you should have your regular committers build with the canonical build env before committing then. Because letting them build with JDK 9 before committing means they can introduce dependencies on new JDK 9 APIs.

And maybe plan to move to git :-)

**Comment by reschke** [comment] 2017-10-23 13:10
> Because letting them build with JDK 9 before committing means they can introduce dependencies on new JDK 9 APIs.

We use the anima-sniffer-plugin as protection.

**Comment by bjhargrave** [comment] 2017-12-08 17:38
Closing.

**Closed by bjhargrave** 2017-12-08 17:38 UTC
