### ISSUE TITLE
Failed to create implicit repository for m2e project

### ISSUE THREAD

**Issue by giamma** [bndtools/bnd#3743] opened 2020-01-27 15:39 UTC
I have a Maven project which contains a bndrun file. The bndrun GUI opens with an empty "repository" list and as a consequence when I push the Resolve button the resolution fails as it cannot find any required capability.

In the Eclipse workspace log I can find the following error:

`Failed to create implicit repository for m2e project test (implicit)
java.lang.NullPointerException
	at bndtools.m2e.MavenImplicitProjectRepository.createRepo(MavenImplicitProjectRepository.java:165)
	at bndtools.m2e.MavenImplicitProjectRunListener$1.run(MavenImplicitProjectRunListener.java:61)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

This problem shows up in Eclipse 2019-09 and 2019-12 when using Bndtools 4.3 or 5.0.
The problem cannot be reproduced when using BndTools 4.2.

**Comment by bjhargrave** [comment] 2020-01-28 16:35
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment] 2020-04-17 15:46
Closing since no information was provided about how to reproduce.

**Closed by bjhargrave** 2020-04-17 15:46 UTC
