### ISSUE TITLE
bnd-resolver-maven-plugin will never report unresolved optional package-imports

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4190] opened 2020-06-24 09:44 UTC
Although according to https://github.com/bndtools/bnd/tree/master/maven/bnd-resolver-maven-plugin#configuration-properties, optional requirements are reported by default as well it does not seem to include optional Package-Import headers. Is there some option on how to report those as well?

**Comment by rotty3000** [comment] 2020-06-24 13:44
I have not experienced this. The flag always seemed to work rather well. But maybe I don't understand the issue completely.
Could you please provide an example to demonstrate?

**Comment by rotty3000** [comment] 2020-06-24 13:45
It should be noted that packages are also materially requirements and will be reported along with other missing requirements in the namespace `osgi.wiring.package`.

**Comment by kwin** [comment] 2020-06-24 14:29
You can find an example at <https://github.com/kwin/jackrabbit-filevault/tree/feature/test-resolver-with-opt-imports>. That fails in module [vault-rcp](https://github.com/kwin/jackrabbit-filevault/tree/feature/test-resolver-with-opt-imports/vault-rcp) with
```
...
[INFO] --- bnd-resolver-maven-plugin:5.1.0:resolve (default) @ org.apache.jackrabbit.vault.rcp ---
[INFO] Bnd inferred -runrequires: osgi.identity;filter:='(osgi.identity=org.apache.jackrabbit.vault.rcp)'
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.apache.jackrabbit.vault.rcp)
          ⇒ [org.apache.jackrabbit.vault.rcp version=3.4.5.SNAPSHOT]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=javax.jcr)(version>=3.0.0))
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.355 s
[INFO] Finished at: 2020-06-24T16:23:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-resolver-maven-plugin:5.1.0:resolve (default) on project org.apache.jackrabbit.vault.rcp: Unable to resolve <<INITIAL>>: missing requirement osgi.identity;filter:='(osgi.identity=org.apache.jackrabbit.vault.rcp)' [caused by: Unable to resolve org.apache.jackrabbit.vault.rcp version=3.4.5.SNAPSHOT: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=javax.jcr)(version>=3.0.0))';osgi.wiring.package='javax.jcr'] -> [Help 1]
[ERROR] 
```
If the import is mandatory (https://github.com/kwin/jackrabbit-filevault/commit/9f0b88465d19bba35a62a4ff54d3db0206db3dad) but succeeds if the import is optional (https://github.com/kwin/jackrabbit-filevault/commit/27d7292dffb25c38f5586991f37732423d1a9059).

**Comment by rotty3000** [comment] 2020-06-24 14:39
Could you please reproduce this in isolation? The repository you point to is very complex.

**Comment by kwin** [comment] 2020-06-24 14:40
I reproduced with another complex example, so I would assume this happens for every optional non-resolvable import. Do you have an example I could extend in that regard? Maybe enRoute?

**Comment by kwin** [comment] 2020-06-24 15:15
Another more simple example at https://github.com/kwin/osgi.enroute/tree/feature/unresolvable-optional-import.
It correctly fails with `mvn package bnd-resolver:resolve` at https://github.com/kwin/osgi.enroute/commit/a008b3d4386d312a3b1c8cc8a061ad52bc284ee0 but emits no warn/info at https://github.com/kwin/osgi.enroute/commit/84bb0b8590b98a723ada0c9d8b4ef5398dfb5eed for module https://github.com/kwin/osgi.enroute/tree/feature/unresolvable-optional-import/examples/microservice/rest-app

**Comment by kwin** [comment] 2020-06-29 12:57
@rotty3000 Is the example provided enough? Do you have any idea yet what might be the issue and if there is a workaround applicable in 5.1.1?

**Comment by rotty3000** [comment] 2020-06-29 13:38
Apologies but I did not yet have time to confirm one way or the other. I will check the last example your point at to see it I can work with it :) Hopefully very shortly.

**Comment by kwin** [comment] 2020-07-08 15:49
@rotty3000 Ping.
Maybe there is just a misunderstanding/misconfiguration in my project so it would be really appreciated if you could confirm this is a bug in Bnd.

**Comment by rotty3000** [comment] 2020-07-08 18:35
(@bjhargrave If you can confirm my understanding it would make me feel better, otherwise just correct me and I'll try to remember for next time).

In order for an optional requirement to be "required" as part of a resolution it needs to include it in the initial requirements in a non-optional way. Otherwise, if left as is, the resolver is free to drop it from the resolution for any reason.

By default the bnd resolver context doesn't actually calculate optional requirements at all (other than to optionally report optional requirements that are found in the non-optional result set.)

Does that help answer your question?

**Comment by bjhargrave** [comment] 2020-07-08 19:41
The `reportOptional` configuration option just tells whether to include `resolution:=optional` requirements from `ResolutionException.getUnresolvedRequirements()` in the report. If the requirement is not in the ResolutionException's unresolved requirements, then it wont make it into any report. 

I suspect that the only way an optional import package will make it into the report is if the resource containing the optional import package is somehow in the resolution failure chain due to some non-optional requirement.  

> If the import is mandatory ([kwin/jackrabbit-filevault@9f0b884](https://github.com/kwin/jackrabbit-filevault/commit/9f0b88465d19bba35a62a4ff54d3db0206db3dad)) but succeeds without any warn/info in the log if the import is optional ([kwin/jackrabbit-filevault@27d7292](https://github.com/kwin/jackrabbit-filevault/commit/27d7292dffb25c38f5586991f37732423d1a9059)).

If a non-optional requirement causes a resolution failure, and changing the requirement to optional makes the resolution succeed, then the resolution succeeded and there it no ResolutionException upon which to report. I am not sure why you think there should be a resolution failure report for a successful resolution? The description for `reportOptional` says:

    If true, resolution failure reports will include optional requirements.

**Comment by bjhargrave** [comment] 2020-07-08 19:47
There is currently no reporting ability on optional requirements which were not satisfied (because as optional requirements, the resolver is permitted to not satisfy them) in a successful resolution.

**Comment by kwin** [comment] 2020-07-09 06:13
Thanks for the clarification. The parameter description for `reportOptional` at https://github.com/bndtools/bnd/tree/master/maven/bnd-resolver-maven-plugin#configuration-properties should be updated then accordingly.

For my use case I would still very much be interested in getting warnings for unresolved optional parameters. WDYT about extending the resolver with an optional flag in that regard? I use the bnd-resolver-maven-plugin to check at build time if my bundle would resolve in certain environments. For one environment I need to make sure that even the optional requirements resolve, while for another environment they don't have to.

**Comment by bjhargrave** [comment] 2020-07-09 14:31
> The parameter description for `reportOptional` at https://github.com/bndtools/bnd/tree/master/maven/bnd-resolver-maven-plugin#configuration-properties should be updated then accordingly.

It already says: `If true, resolution failure reports will include optional requirements.` Which I think is entirely accurate. The parameter does not cause a report, it just influences the contents of a report if a report is made.


> For my use case I would still very much be interested in getting warnings for unresolved optional parameters. WDYT about extending the resolver with an optional flag in that regard?

Bnd (like Eclipse Equinox and Apache Felix) use the Apache Felix Resolver implementation. So if you want to change the resolver, you will need to do any changes in that project. The resolver is quite complicated.

> For one environment I need to make sure that even the optional requirements resolve, while for another environment they don't have to.

I will also note, that a resolver is not required to solve all optional requirements even if a solution is possible. Sometime the solution space is quite large, so a resolver can choose a solution which does not solve all optional requirements in order to reduce the amount of time spent looking for the "best" solution. So you may never be able to reliably generate a resolve solution in which all optional requirements are solved.

**Comment by rotty3000** [comment] 2020-07-09 14:37
Following what @bjhargrave has stated, it is possible to force optional requirements to resolve by hoisting them into the intitial requirements and bypassing their optional nature. This is precisely the mechanic used in bndtools when a resolution result window is presented which lists the set of optional requirements. If in that dialog you choose to include any optional requirements from that set, they are hoisted into the initial requirements and then the resolution is re-calculated as if those are no longer optional.

If you wish to "test" the validity of optional requirements (for example to ensure they _could_ be resolved) then you can create multiple different bndrun files which have hoisted said optional requirements up in this way and then attempt to resolve those.

**Comment by bjhargrave** [comment] 2020-07-10 16:08
What we may want to do is to add a config option to run the resolve, and if successful, hoist all unsolved optional requirements up into mandatory requirements and re-run the resolve.

**Comment by bjhargrave** [comment] 2021-11-12 16:34
Closing.

**Closed by bjhargrave** 2021-11-12 16:34 UTC
