### ISSUE TITLE
bnd stuck when parent class is a Scala class

### ISSUE THREAD

**Issue by lexsoto** [bndtools/bnd#1483] opened 2016-06-01 19:25 UTC
When the component class extends a Scala class, the plugin never finishes, and the CPU level goes to 100%.  Process needs to be killed.

Example: 

`import org.osgi.service.component.annotations.Component;
import akka.actor.UntypedActor;

@Component
public class MyClass extends UntypedActor {`

**Comment by bjhargrave** [comment] 2016-06-10 16:12
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by lexsoto** [comment] 2016-06-10 16:36
Sure, will take me a couple of days.

**Comment by lexsoto** [comment] 2016-06-17 19:31
I am sorry about the delay.   I created a minimal project that reproduces the issue.  You can access it here:

https://github.com/lexsoto/osgi-ds-akka

Thanks!

**Comment by djencks** [comment] 2016-07-18 21:40
I believe this sample project uses the maven-bundle-plugin version 2.3.7 which uses bnd 1.50:
<dependency><groupId>biz.aQute</groupId><artifactId>bndlib</artifactId><version>1.50.0</version></dependency>

Could you see if there is a problem with bnd 3.2?  There is definitely some code present in the current bnd version that attempts to deal with Scala superclasses.

**Comment by bjhargrave** [comment] 2016-07-22 16:26
Closing. Please file a new issue if the problem is still in bndlib 3.2 or later.

**Closed by bjhargrave** 2016-07-22 16:26 UTC
