### ISSUE TITLE
Bnd resolve task emits unexportable version requirement

### ISSUE THREAD

**Issue by gamerson** [bndtools/bnd#3762] opened 2020-02-05 20:52 UTC
I have a sample workspace here using bnd 5.1.0-SNAPSHOT

https://github.com/gamerson/eclipse-headless-bnd

In this workspace, if you clone it and do the following...

1. `cd eclipse.headless.app`
2. `../gradlew resolve`
3. `../gradlew export`

It will fail with the following error:

```
 Task :eclipse.headless.app:export.app FAILED
error  : Can not find URL for bsn bndtools.runtime.applaunch.eclipse4
error  : bndtools.runtime.applaunch.eclipse4;version=snapshot not found

FAILURE: Build failed with an exception.
```

If you go to the `app.bndrun` and remove the following line:
```
bndtools.runtime.applaunch.eclipse4;version=snapshot
```
with this line
```
bndtools.runtime.applaunch.eclipse4
```

And then try the `gradlew export`, it will work and correctly exports an executable jar.

This bundle `bndtools.runtime.applaunch.eclipse4` is coming from a Bnd workspace `Local` repository.  It has the version of `0.1.0.20141204-0657`

**Comment by bjhargrave** [comment] 2020-02-07 18:25
So after some debugging, the issue is that the `bndtools.runtime.applaunch.eclipse4` artifact is in a `LocalIndexedRepo`. That repo type always decorates resources in its index as having come from the workspace. That is, is adds a `bnd.workspace.project` capability whose `bnd.workspace.project` attribute has a value of the URI of the index file to the resource.

This is wrong. Only the `WorkspaceResourcesRepository` should decorate resources with a `bnd.workspace.project` capability. Things in a `LocalIndexedRepo` are in the repo. They may have come from the workspace before being released into the repo. But once they are in the repo, the resource comes from the repo and not the workspace.

**Closed** 2020-02-07 20:13 UTC
Labels: maint-candidate
