### ISSUE TITLE
Baseline doesn't seem to take bytecode versions into account

### ISSUE THREAD

**Issue by io7m** [bndtools/bnd#5209] opened 2022-04-10 15:30 UTC
I was surprised to discover that the `bnd` baseline tool doesn't seem to take bytecode versions into account, despite the fact that this can yield completely binary-incompatible artifacts.

A test repos is here:

https://github.com/io7m/bnd-baseline-issue-20220410

Note that the code first compiles a class as Java 11 bytecode, and packages it into a bundle using an utterly minimal manifest. It then compiles the same class again but as Java 17 bytecode, and packages it into a second bundle using the same manifest. It then runs `bnd baseline` on both bundles, and is told that they're patch-version compatible. They clearly aren't; If I load the second bundle on a Java 11 VM, I'll get a runtime error.

The tool should treat a bytecode version increase like this as a binary-incompatible change, just as the `japicmp` tool does.

**Comment by rotty3000** [comment] 2022-04-10 15:51
your bnd basline command is backward. `bnd baseline newer older`

in other words can you change you test to be:

```
bnd baseline bundle17.jar bundle11.jar
```
and let's see if you get the same result.

**Comment by io7m** [comment] 2022-04-10 15:53
Oops, my mistake! However, the result is the same:

```
$ bnd baseline bundle17.jar bundle11.jar 
===============================================================
* com.io7m.example 1.0.0-1.0.0 suggests 1.0.1
===============================================================
```

I actually discovered this via the `bnd-baseline-plugin` in a Maven build; I expected to get a baseline error when I started requiring JDK 17 bytecode, but it didn't happen.

**Comment by rotty3000** [comment] 2022-04-10 15:53
thx for confirming.

**Comment by rotty3000** [comment] 2022-04-10 15:55
I would have assumed that this would have been caught by the mere fact of resources being different.

**Comment by timothyjward** [comment] 2022-04-10 15:55
> The tool should treat a bytecode version increase like this as a binary-incompatible change

I’m not sure I agree with this. The Java 17 version will not be resolvable on the Java 11 framework due to the `osgi.ee` requirement. 
OSGi baselining is about how the bytecode will link at runtime, assuming that the Java runtime is able to load both classes.

**Comment by io7m** [comment] 2022-04-10 16:04
I see your point but, from a purely practical point of view, not making this (relatively simple) check means that I'd have to introduce both `japicmp` and `bnd-baseline-plugin` into my builds despite the binary compatibility checking of `bnd` subsuming that of `japicmp` in every manner except for this one check.

**Comment by io7m** [comment] 2022-04-10 16:07
For that matter, the baseline doesn't seem to catch the change in `osgi.ee` either:

```
$ bnd print com.io7m.jtensors.core-10.0.0.jar | grep ee
Require-Capability                      osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"

$ bnd print com.io7m.jtensors.core-10.1.0-SNAPSHOT.jar | grep ee
Require-Capability                      osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=17))"

$ bnd baseline com.io7m.jtensors.core-10.1.0-SNAPSHOT.jar com.io7m.jtensors.core-10.0.0.jar 
===============================================================
  com.io7m.jtensors.core 10.1.0.SNAPSHOT-10.0.0
===============================================================
  Package                                            Delta      New        Old        Suggest    If Prov.  
  com.io7m.jtensors.core.parameterized               ADDED      10.0.0     -          ok         -         
  com.io7m.jtensors.core.parameterized.vectors       MINOR      10.1.0     10.0.0     ok         -         
  com.io7m.jtensors.core.unparameterized             ADDED      10.0.0     -          ok         -         
```

**Comment by timothyjward** [comment] 2022-04-10 16:14
The problem is that the baselining change you are proposing breaks the OSGi versioning rules. If we have identical sources for API `X.Y.Z` compiled for Java 11, and for Java 17, and a client of that API compiled for Java 11 using the Java 11 `X.Y.Z` then that client is guaranteed to still work on Java 17 when using either variant of `X.Y.Z`. That’s why they baseline as the same package version. 

> For that matter, the baseline doesn't seem to catch the change in osgi.ee either:

The example above has two different ee versions required, and the bundle version appears to have already been moved from 10.0 to 10.1. The ee requirement would be a bundle version issue, not a package version issue.

**Comment by io7m** [comment] 2022-04-10 16:19
> The problem is that the baselining change you are proposing breaks the OSGi versioning rules.

I see.

> The example above has two different ee versions required, and the bundle version appears to have already been moved from 10.0 to 10.1...

I'm not sure I understand this one. `10.0.0` (which is actually the bundle version, not just the package version(s)` required `osgi.ee` 11, whilst `10.1.0` requires `osgi.ee` 17, and this is considered to be a backwards-compatible change? `10.1.0` won't resolve in a container running on a Java 11 VM.

**Comment by timothyjward** [comment] 2022-04-10 16:30
> 10.1.0 won't resolve in a container running on a Java 11 VM.

This is true, but baselining isn’t about whether a bundle will resolve (the resolver plugin deals with this). Baselining is strictly about API compatibility, and changing bytecode version isn’t part of that. If the package were `java.something` and came from the JVM then it’s bytecode version would also change between Java 11 and Java 17, but it wouldn’t be a breaking change unless the API had actually changed in an incompatible way.

**Comment by io7m** [comment] 2022-04-10 16:48
I'm a little unsure how to proceed.

Is there _any_ way to express the check I'm looking for? The bundles I publish are also plain Java libraries, and in that world, increasing the required bytecode version is certainly considered a breaking change deserving of a major version number increase.

I don't want to accidentally screw things up for anyone depending on my code because I released JDK 18 bytecode when I intended to stick to 17 everywhere, and the tools didn't tell me I should have raised the major version number before I did that.

I can use the Maven Enforcer plugin to enforce a bytecode version, but obviously that plugin knows nothing about package/bundle/library versioning and will (for example) happily start enforcing a new bytecode version when I update a parent pom, despite not incrementing the version number at all in the consuming project.

Perhaps checking that the `osgi.ee` value hasn't increased would be enough, but from what I can tell, this isn't considered the responsibility of any of the existing `bnd` plugins.

**Comment by timothyjward** [comment] 2022-04-10 17:29
> Perhaps checking that the osgi.ee value hasn't increased would be enough, but from what I can tell, this isn't considered the responsibility of any of the existing bnd plugins.

You want theresolver

**Comment by rotty3000** [comment] 2022-04-10 23:54
I've personally come to the conclusion that, for this and several other reasons, using resolver plugin during normal build serves more than simply assembling runtimes. It serves to:

1. assert that a bundle actually can resolve ("libraries", which have OSGi metadata but sadly cannot actually work in OSGi as they are, are far too common) 
1. asserts a probable set of dependencies (perhaps even specific dependencies) 
1. highlight the runtime dependencies a bundle may inadvertently accrete over time
1. assert (as @timothyjward suggested) the minimum Java version required

**Comment by io7m** [comment] 2022-04-11 10:57
Is it feasible to use the resolver plugin for individual modules? 90% of what I produce is library code. If this is something I can add in a parent POM and have the check execute for individual modules in all of my projects, then I'd be happy with that.

My understanding was more that the resolver plugin was used to resolve bundles in `.bndrun` files (and I've used it for that in the past).

**Comment by io7m** [comment] 2022-04-11 10:59
I guess the check would be phrased as "can version `n` of this bundle resolve in the same circumstances that version `m` would resolve, where `n < m` and the circumstances largely involve `osgi.ee`"

**Comment by timothyjward** [comment] 2022-04-11 12:24
> I guess the check would be phrased as "can version m of this bundle resolve in the same circumstances that version n would resolve, where n < m and the circumstances largely involve osgi.ee"

Pretty much - the resolve check will also tell you if new dependencies have been added, or dependency versions have changed. This can be really useful for seeing when changes you have made have unexpected consequences, including something as simple as "this dependency now requires Java 17 so I can't run on Java 11", or "did I really mean to require a new version of the Servlet API?".

Effectively you set up a bndrun with a requirement for the latest version of your bundle and resolve it "manually" (i.e. with the command line or the Bndtools resolve button). You persist this result by checking it into SCM. You then run a "validation resolve" in your CI builds which checks that running the resolver against your latest build output still gives the same result. A failure indicates that either:

- The change broke something and should be fixed or reverted to avoid the breaking change
- The change in resolution is acceptable, so you do an update of the bndrun and check it in.

Ideally you will run a build yourself locally before checking in, which shows a failure pre commit. You can then decide how to fix before committing if needed. If you forget (or just like to live dangerously) then CI can catch it for you.

The version `n` to `m` change then becomes an update to the pom (as normal), which will break the resolve check in the build (the version of your bundle(s) has/have changed). If fixing the resolve requires more than updating the version range(s) for the bundle(s) built in your build then you have the answer to
> "can version m of this bundle resolve in the same circumstances that version n would resolve, where n < m and the circumstances largely involve osgi.ee"

**Comment by rotty3000** [comment] 2022-04-11 13:47
Some libraries that are doing this:
- [JUnit5](https://github.com/junit-team/junit5/blob/main/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts#L92-L104)
- [Mockito](https://github.com/mockito/mockito/blob/main/subprojects/junit-jupiter/junit-jupiter.gradle#L50-L54)
- [Spock Framework](https://github.com/spockframework/spock/blob/e9d5ece38cb096d835fd19fff771980846a50d9c/spock-core/core.gradle#L102-L106)

This is a particularly nice practice for those who do not have OSGi top of mind (which is totally fine.) It makes it much easier for those teams because they can see real failures as early as possible.

**Comment by bjhargrave** [comment] 2022-04-11 18:37
Baselining is about binary compatibility of API signatures (as defined by the JLS) and semantically versioning the API signature to properly convey the binary compatibility relative to prior released versions of the API signature.

It is not at all about implementation details. Implementation details like which other APIs are used in method bodies or which Java versions are the class files is conveyed by requirements such as Import-Package and Require-Capability.  Checking on the acceptability of changes to requirements is a job for the resolver (as mentioned above) and not the baseliner.

So, to close out this issue, baselining will not care about Java class file versions as that is an implementation detail and not an part of the binary compatibility of the API signature.

**Comment by bjhargrave** [comment] 2022-04-14 13:23
I am closing this issue since bytecode version is an implementation detail and not part of the API signatures which is the thing that is baselined.

**Closed by bjhargrave** 2022-04-14 13:23 UTC
