### ISSUE TITLE
BND 5.2.0 uses deprecated Gradle ProjectLayout.configurableFiles() method

### ISSUE THREAD

**Issue by mjpt777** [bndtools/bnd#4516] opened 2021-01-27 17:09 UTC
Happens with building with Gradle 6.7+.

```
The ProjectLayout.configurableFiles() method has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the ObjectFactory.fileCollection() method instead. See https://docs.gradle.org/6.8.1/userguide/lazy_configuration.html#property_files_api_reference for more details.
```

**Comment by bjhargrave** [comment] 2021-01-27 18:35
Duplicate of #4451

**Closed by bjhargrave** 2021-01-27 18:35 UTC
