### ISSUE TITLE
bndtools: Regression in re-running OSGi JUnit tests

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4813] opened 2021-08-30 12:16 UTC
Something about test rerunning is wrong in Bndtools now. After running an OSGi JUnit test, you used to be able to click the rerun button to run the test again. Now that does nothing. If you select the test name in the Junit view and click Run or Debug, you get a strange dialog. This is regression from 5.3

https://user-images.githubusercontent.com/277682/131337433-f40941e5-c2a0-4081-bc9c-9940e4e7733a.mov

This is a real productivity drop since I have to go back to the explorer view to find the test project and do Run OSGi JUnit again…

**Comment by bjhargrave** [comment] 2021-08-30 12:41
This needs to be solved before we can finish 6.0. It is a bad usability regression.

**Comment by kriegfrj** [comment] 2021-08-31 05:32
To be fixed in conjunction with #3709. I'm currently working on this.

**Comment by kriegfrj** [comment] 2021-08-31 05:43
For posterity, I think the root cause of this regression is here: 

https://github.com/bndtools/bnd/blob/edaa23cb5f90b685798910d56025143a95104c44/org.bndtools.launch/src/bndtools/launch/OSGiJUnitLaunchDelegate.java#L219-L229

If this returns the actual `ILaunch` instance that was used to launch the test, then the JUnit Core uses that to get the associated `ILaunchConfiguration` and re-launch it. If it is `null` (or its launch configuration is `null`), it takes the alternative code path that results in the error message that you're seeing.

I'll need to see if I can find a way to make this work without undoing what I accomplished in #4717.

In the meantime, it is *almost* as easy in Eclipse to re-run the last test run from the Run or Debug toolbar button (you don't need to find the test project again).

**Closed** 2021-09-08 15:51 UTC

**Comment by bjhargrave** [comment] 2021-09-10 16:52
Thanks for fixing. It seems back to normal now!
