### ISSUE TITLE
StackOverflowError running gradle build or opening in eclipse + bndtools

### ISSUE THREAD

**Issue by djencks** [bndtools/bnd#795] opened 2015-01-31 20:06 UTC
I'm getting a StackOverflowError immediately on the osgi project running the gradle build or opening in eclipse + bndtools:

	at aQute.bnd.osgi.Analyzer.getBsn(Analyzer.java:1051)
	at aQute.bnd.build.ProjectBuilder.toString(ProjectBuilder.java:486)
	at aQute.bnd.osgi.Processor.formatArrays(Processor.java:1908)
	at aQute.bnd.osgi.Processor.warning(Processor.java:170)
	at aQute.bnd.osgi.Macro.replace(Macro.java:228)
	at aQute.bnd.osgi.Macro.process(Macro.java:73)
	at aQute.bnd.osgi.Macro.process(Macro.java:89)
	at aQute.bnd.osgi.Macro.process(Macro.java:59)
	at aQute.bnd.osgi.Macro.process(Macro.java:54)
	at aQute.bnd.osgi.Processor.getProperty(Processor.java:1189)
	at aQute.bnd.osgi.Processor.getProperty(Processor.java:1135)
	at aQute.bnd.osgi.Processor.getProperty(Processor.java:826)
	at aQute.bnd.osgi.Analyzer.getBsn(Analyzer.java:1051)

**Comment by timothyjward** [comment] 2015-01-31 20:14
Hi,

This is usually caused by telling Include-Resource to process a large file for macros. 

Try removing any braces from your bnd file (unless you put them there deliberately). Braces tell bnd to do macro processing on the resource.

I hope this helps.

**Comment by djencks** [comment] 2015-01-31 20:19
This is trying to build the osgi git checkout, unmodified.  IMO bnd should not get into this loop, no matter what causes it.

**Comment by bjhargrave** [comment] 2015-01-31 20:39
@djencks You seem to be the only person I know of with this issue. No one else in OSGi has this issue and can build the OSGi repo just fine. So there must be some other issue with your system. I know you have an old OS X version and thus an old git client. Can you clean your checked out repo and zip/tar it up for me? I am wondering if the old git client is messing things up. 

What is the file system you checked the repo into? HFS+? case sensitive?

**Comment by bjhargrave** [comment] 2015-01-31 20:53
I just found an OS X 10.8.5 vmware image and am installing the command line tools for Mountain Lion (10.8) to get the git command so I can try and reproduce @djencks problem.

**Comment by bjhargrave** [comment] 2015-01-31 21:13
OK. I have a 10.8.5 system running in vmware. It had no command line tools and no java. So I downloaded the Command Line tools for Mountain Lion from Apple <https://developer.apple.com/downloads/index.action> and JDK 6 from Apple <http://support.apple.com/kb/DL1572>. I cloned the OSGi build repo and checked out the `cmpn` branch.

    BJs-Mac:~ hargrave$ cd git/build
    BJs-Mac:build hargrave$ pwd
    /Users/hargrave/git/build
    BJs-Mac:build hargrave$ git --version
    git version 1.8.5.2 (Apple Git-48)
    BJs-Mac:build hargrave$ javac -version
    javac 1.6.0_65
    BJs-Mac:build hargrave$ ./gradlew --version
    
    ------------------------------------------------------------
    Gradle 2.1
    ------------------------------------------------------------
    
    Build time:   2014-09-08 10:40:39 UTC
    Build number: none
    Revision:     e6cf70745ac11fa943e19294d19a2c527a669a53
    
    Groovy:       2.3.6
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.6.0_65 (Apple Inc. 20.65-b04-466.1)
    OS:           Mac OS X 10.8.5 x86_64
    
    BJs-Mac:build hargrave$ git branch
    * cmpn
      master
    BJs-Mac:build hargrave$  

I then started the build and gradle is just running fine:

    BJs-Mac:build hargrave$ ./gradlew
    :cnf:compileJava
    :cnf:processResources UP-TO-DATE
    :cnf:classes
    :cnf:refresh
    :cnf:jar SKIPPED
    :cnf:assemble UP-TO-DATE
    :ee.foundation:compileJava
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    :ee.foundation:processResources UP-TO-DATE
    :ee.foundation:classes
    :ee.foundation:jar
    Warning: Unused Export-Package instructions: [java.*] 
    :ee.foundation:assemble
    :ee.minimum:compileJava
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    :ee.minimum:processResources UP-TO-DATE
    :ee.minimum:classes
    :ee.minimum:jar
    Warning: Unused Export-Package instructions: [java.*] 
    :ee.minimum:assemble
    :org.osgi.annotation.versioning:compileJava
    ...

No problems building. 

I don't have any idea what is wrong with your system @djencks. Perhaps you can update your command line tools to get a more recent git (yours was a 1.7 version if I recall) and also install Java 6 which is what we use for the OSGi build for the cmpn branch on the OSGi server. But whatever problem you have seems to be completely isolated to your system. :-(

**Comment by pkriens** [comment] 2015-02-06 17:23
David, can you verify if this works? Can we close this?

**Comment by bjhargrave** [comment] 2015-02-19 13:55
@djencks See if #818 solves your problem. Your stack trace seems very similar to the one described in #724 (and fixed by #818)

**Comment by bjhargrave** [comment] 2015-02-20 17:26
Closing. Reopen if this is not fixed by #818

**Closed by bjhargrave** 2015-02-20 17:26 UTC
