### ISSUE TITLE
[cli]

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3162] opened 2019-04-25 12:23 UTC
When generating bundles via cli non-.class ressources does not exist in the bundle.
```
commands:
biz.aQute.bnd.jar **build**
biz.aQute.bnd.jar **_par**
```

**Comment by bjhargrave** [comment] 2019-04-25 13:04
I have not idea what the issue is here. The subject line is non-descriptive and the body does not provide anywhere near enough information to describe a problem. Please improve this issue.

**Comment by stbischof** [comment] 2019-04-25 13:23
Sorry, i made a PR parallel.  Saved Issue by accident.

**Comment by bjhargrave** [comment] 2019-04-25 13:25
>  Saved Issue by accident.

OK, Closing then.

**Closed by bjhargrave** 2019-04-25 13:25 UTC
