### ISSUE TITLE
ArrayIndexOutOfBoundsException in resolve

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#3357] opened 2019-07-24 09:48 UTC
Using bnd-export-maven-plugin 4.2.0 to resolve a bndrun file, I get the following ArrayIndexOutOfBoundException:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData (ArrayList.java:422)
    at java.util.ArrayList.set (ArrayList.java:450)
    at org.apache.felix.resolver.util.ShadowList.replace (ShadowList.java:74)
    at org.apache.felix.resolver.Candidates.prepare (Candidates.java:939)
    at org.apache.felix.resolver.ResolverImpl.getInitialCandidates (ResolverImpl.java:547)
    at org.apache.felix.resolver.ResolverImpl.doResolve (ResolverImpl.java:432)
    at org.apache.felix.resolver.ResolverImpl.resolve (ResolverImpl.java:421)
    at org.apache.felix.resolver.ResolverImpl.resolve (ResolverImpl.java:375)
    at biz.aQute.resolve.BndResolver.resolve (BndResolver.java:32)
    at biz.aQute.resolve.ResolveProcess.resolveRequired (ResolveProcess.java:81)
    at biz.aQute.resolve.ProjectResolver.resolve (ProjectResolver.java:105)
    at biz.aQute.resolve.Bndrun.resolve (Bndrun.java:95)
    at biz.aQute.resolve.Bndrun.resolve (Bndrun.java:88)
    at aQute.bnd.maven.export.plugin.ExportMojo.lambda$getOperation$0 (ExportMojo.java:145)
    at aQute.bnd.maven.lib.resolve.BndrunContainer.execute (BndrunContainer.java:190)
    at aQute.bnd.maven.export.plugin.ExportMojo.execute (ExportMojo.java:131)
```

This problem happens when I include a fragment bundle in the `-runrequires` list.

**Comment by timothyjward** [comment] 2019-07-24 14:19
Didn't @rotty3000 fix this for 4.3.0 already?

**Comment by bjhargrave** [comment] 2019-07-24 14:29
Yes. I had that same thought.

**Comment by njbartlett** [comment] 2019-07-24 14:32
I couldn't find any other bugs referencing an ArrayIndexOutOfBoundsException, except for #1472 which is old (3.3).

**Comment by bjhargrave** [comment] 2019-07-24 14:34
Have you tried 4.3 to see if the issue is still present?

**Comment by njbartlett** [comment] 2019-07-24 15:07
Have just tried 4.3 and the issue is indeed still present:

```
[INFO] --- bnd-export-maven-plugin:4.3.0-SNAPSHOT:export (default) @ osgi-assembly ---
[ERROR] Error   : Exception: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.set(ArrayList.java:450)
	at org.apache.felix.resolver.util.ShadowList.replace(ShadowList.java:74)
	at org.apache.felix.resolver.Candidates.prepare(Candidates.java:939)
	at org.apache.felix.resolver.ResolverImpl.getInitialCandidates(ResolverImpl.java:547)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:432)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:421)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:32)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:81)
	at biz.aQute.resolve.RunResolution.resolve(RunResolution.java:71)
	at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:103)
	at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:91)
	at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:85)
	at aQute.bnd.maven.export.plugin.ExportMojo.lambda$getOperation$0(ExportMojo.java:146)
```

**Comment by bjhargrave** [comment] 2019-07-24 15:33
I remember that I made a fix for something similar to this. The fix was in how Bnd generated the capabilities for the framework since we need to handle the system.bundle alias. We had originally put in 2 osgi.identity capabilities which is invalid. Now it uses a List for the value with 2 elements.  You mention fragments in your initial description. I am on holiday now, so I don’t have my computer.

**Comment by njbartlett** [comment] 2019-07-24 15:51
Thanks. I have stripped down my project to create a reproducible example of the bug. Just build this with `mvn -e clean package`: https://github.com/njbartlett/bnd-bug-3357

**Comment by rotty3000** [comment] 2019-07-24 15:59
I know this can and does work since it's used there https://github.com/rotty3000/com.github.rotty3000.examples/blob/master/com.github.rotty3000.cdi.jaxrs/test.bndrun#L39

**Comment by rotty3000** [comment] 2019-07-24 16:15
I don't see what satisfies this `Fragment-Host: org.eclipse.swt`

**Comment by njbartlett** [comment] 2019-07-24 18:54
@rotty3000 It should be satisfied by the `-runsystemcapabilities` in assembly.bndrun.

**Comment by stbischof** [comment] 2019-07-24 20:43
the other arrayindexoutofbounds you may remember @bjhargrave was maybe this 
https://github.com/bndtools/bnd/issues/2695

**Comment by bjhargrave** [comment] 2019-08-02 16:49
The `-runsystemcapabilities` is bad here. You are adding a second `osgi.wiring.host` capability to the framework resource and the resolver will break on this. You cannot add additional framework namespace capabilities to the framework resource like this.

Potential Bnd fixes:

1. Detect using framework namespaces in `-runsystemcapabilities` and error.
2. Detect using framework namespaces in `-runsystemcapabilities` and merge the information into the existing framework capabilities.

**Comment by rotty3000** [comment] 2019-08-02 17:47
One thing I'm not clear about @njbartlett is why the following isn't a solution (this worked for me):

in `javafx.swt/bnd.bnd`:
```
-Fragment-Host: org.eclipse.swt
+Fragment-Host: system.bundle
```
since that's effectively what you're doing.

Otherwise, I can only guess you're trying to model what @bjhargrave has explained above. I just don't see how that is useful in any real scenario. It seems like you may be trying to, as @bjhargrave put it, _shut up the resolver_? I still don't see why that really helps.

**Comment by njbartlett** [comment] 2019-08-02 18:20
No that's not my intention.

I want to use bnd resolution to export a set of bundles. These bundles will be post-processed into a repository that can be consumed in Eclipse (Tycho) as a Target Platform. When that happens, its content will be combined with other repositories/targets.

My repository needs to contain a bundle that has a dependency of `org.eclipse.swt` but I don't want the repository to actually contain `org.eclipse.swt`. Adding the capability to `-runsystemcapabilities` is a hacky way to make the bndrun resolve without actually including `org.eclipse.swt` as a bundle in the output.

Maybe there is a better way to do this... I almost need some kind of platform or profile definition.

Anyway the point is now moot because I found a way to make my `javafx.swt` bundle work as a full bundle (with `Require-Bundle: org.eclipse.swt`) rather than a fragment. When I use the `osgi.wiring.bundle` namespace in the system capability instead of `osgi.wiring.host`, everything works fine.

**Comment by zhsc** [comment] 2019-11-23 02:19
This looks similar to an issue I had that @bjhargrave fixed previously https://github.com/bndtools/bnd/issues/2264

**Comment by bjhargrave** [comment] 2020-06-26 15:18
Closing as we have made many fixes to the resolve context.

**Closed by bjhargrave** 2020-06-26 15:18 UTC
