### ISSUE TITLE
How to embed all transitive dependencies

### ISSUE THREAD

**Issue by viveksachdeva** [bndtools/bnd#4971] opened 2021-11-30 12:55 UTC
Previously we used to specify Embed-Transitive tag as true to auto include all transitive dependencies. Do we have a replacement for that in bnd-maven-plugin?

**Comment by bjhargrave** [comment] 2021-11-30 18:23
This is a duplicate of #4894 which was closed. See [my comment](https://github.com/bndtools/bnd/issues/4894#issuecomment-944284286) for suggested alternatives.

**Closed by bjhargrave** 2021-11-30 18:23 UTC
