### ISSUE TITLE
Proper snapshot release not created when uploading to Artifactory, causing maven-metadata.xml not being updated properly

### ISSUE THREAD

**Issue by Mr-Frantic** [bndtools/bnd#1566] opened 2016-07-28 13:59 UTC
When uploading to artifactory using 
gradle clean build release

bnd uploads the snapshot version with a the same buildnumber.

Artifacts can be read like this : <artifactId>-<major version>.<minor version>.<incremental version>-<qualifier>-<buildNumber>

Here is the example on how the artifacts looks when deployed using maven and bnd:

This is how the maven deployed artifacts looks like in artifactory:

comcast-1.0.0-20150914.070543-1.pom 14-Sep-2015 09:05 1.16 KB
comcast-1.0.0-20150914.070543-1.pom.md5 14-Sep-2015 09:05 32 bytes
comcast-1.0.0-20150914.070543-1.pom.sha1 14-Sep-2015 09:05 40 bytes
comcast-1.0.0-20150929.071412-2.pom 29-Sep-2015 09:14 1.16 KB
comcast-1.0.0-20150929.071412-2.pom.md5 29-Sep-2015 09:14 32 bytes
comcast-1.0.0-20150929.071412-2.pom.sha1 29-Sep-2015 09:14 40 bytes
comcast-1.0.0-20160211.065600-3.pom 11-Feb-2016 07:56 1.16 KB
comcast-1.0.0-20160211.065600-3.pom.md5 11-Feb-2016 07:56 32 bytes
comcast-1.0.0-20160211.065600-3.pom.sha1 11-Feb-2016 07:56 40 bytes
maven-metadata.xml 11-Feb-2016 07:56 588 bytes
maven-metadata.xml.md5 11-Feb-2016 07:56 32 bytes
maven-metadata.xml.sha1 11-Feb-2016 07:56 40 bytes

Whereas bnd deployed artifacts looks like:

cpi.camunda-0.0.0-20160711.152904-1-javadoc.jar 11-Jul-2016 17:29 69.24 KB
cpi.camunda-0.0.0-20160711.152904-1-javadoc.jar.md5 11-Jul-2016 17:29 32 bytes
cpi.camunda-0.0.0-20160711.152904-1-javadoc.jar.sha1 11-Jul-2016 17:29 40 bytes
cpi.camunda-0.0.0-20160711.152904-1-sources.jar 11-Jul-2016 17:29 12.79 KB
cpi.camunda-0.0.0-20160711.152904-1-sources.jar.md5 11-Jul-2016 17:29 32 bytes
cpi.camunda-0.0.0-20160711.152904-1-sources.jar.sha1 11-Jul-2016 17:29 40 bytes
cpi.camunda-0.0.0-20160711.152904-1.jar 11-Jul-2016 17:29 33.05 KB
cpi.camunda-0.0.0-20160711.152904-1.jar.md5 11-Jul-2016 17:29 32 bytes
cpi.camunda-0.0.0-20160711.152904-1.jar.sha1 11-Jul-2016 17:29 40 bytes
cpi.camunda-0.0.0-20160711.152904-1.pom 11-Jul-2016 17:29 525 bytes
cpi.camunda-0.0.0-20160711.152904-1.pom.md5 11-Jul-2016 17:29 32 bytes
cpi.camunda-0.0.0-20160711.152904-1.pom.sha1 11-Jul-2016 17:29 40 bytes
cpi.camunda-0.0.0-20160719.130151-1-javadoc.jar 19-Jul-2016 15:01 65.04 KB
cpi.camunda-0.0.0-20160719.130151-1-javadoc.jar.md5 19-Jul-2016 15:01 32 bytes
cpi.camunda-0.0.0-20160719.130151-1-javadoc.jar.sha1 19-Jul-2016 15:01 40 bytes
cpi.camunda-0.0.0-20160719.130151-1-sources.jar 19-Jul-2016 15:02 12.46 KB
cpi.camunda-0.0.0-20160719.130151-1-sources.jar.md5 19-Jul-2016 15:02 32 bytes
cpi.camunda-0.0.0-20160719.130151-1-sources.jar.sha1 19-Jul-2016 15:02 40 bytes
cpi.camunda-0.0.0-20160719.130151-1.jar 19-Jul-2016 15:01 32.32 KB
cpi.camunda-0.0.0-20160719.130151-1.jar.md5 19-Jul-2016 15:01 32 bytes
cpi.camunda-0.0.0-20160719.130151-1.jar.sha1 19-Jul-2016 15:01 40 bytes
cpi.camunda-0.0.0-20160719.130151-1.pom 19-Jul-2016 15:01 525 bytes
cpi.camunda-0.0.0-20160719.130151-1.pom.md5 19-Jul-2016 15:01 32 bytes
cpi.camunda-0.0.0-20160719.130151-1.pom.sha1 19-Jul-2016 15:01 40 bytes
cpi.camunda-0.0.0-20160719.131427-1-javadoc.jar 19-Jul-2016 15:14 65.02 KB
cpi.camunda-0.0.0-20160719.131427-1-javadoc.jar.md5 19-Jul-2016 15:14 32 bytes
cpi.camunda-0.0.0-20160719.131427-1-javadoc.jar.sha1 19-Jul-2016 15:14 40 bytes
cpi.camunda-0.0.0-20160719.131427-1-sources.jar 19-Jul-2016 15:14 12.46 KB
cpi.camunda-0.0.0-20160719.131427-1-sources.jar.md5 19-Jul-2016 15:14 32 bytes
cpi.camunda-0.0.0-20160719.131427-1-sources.jar.sha1 19-Jul-2016 15:14 40 bytes
cpi.camunda-0.0.0-20160719.131427-1.jar 19-Jul-2016 15:14 32.32 KB
cpi.camunda-0.0.0-20160719.131427-1.jar.md5 19-Jul-2016 15:14 32 bytes
cpi.camunda-0.0.0-20160719.131427-1.jar.sha1 19-Jul-2016 15:14 40 bytes
cpi.camunda-0.0.0-20160719.131427-1.pom 19-Jul-2016 15:14 525 bytes
cpi.camunda-0.0.0-20160719.131427-1.pom.md5 19-Jul-2016 15:14 32 bytes
cpi.camunda-0.0.0-20160719.131427-1.pom.sha1 19-Jul-2016 15:14 40 bytes
...
maven-metadata.xml 23-Jul-2016 20:45 1.18 KB
maven-metadata.xml.md5 23-Jul-2016 20:45 32 bytes
maven-metadata.xml.sha1 23-Jul-2016 20:45 40 bytes

What I see is whenever I upload using bndtools/bnd the buildNumber is always 1 and due to this the value in maven-metadata.xml is not updating.

I also raised a issue for uploading to artifactory https://groups.google.com/forum/#!searchin/bndtools-users/artifactory/bndtools-users/sUpy-uxQ-50/aO3vwUOcBgAJ which fixed the issue for upload to artifactory, but I still have issues of maven-metadata.xml not being updated properly.

**Comment by bjhargrave** [comment] 2016-08-11 20:25
See https://groups.google.com/forum/#!topic/bndtools-users/lzudg5sG86w for the email thread.

**Comment by eliasvasylenko** [comment] 2017-04-04 14:51
A suggestion ... does artifactory expect/need the build numbers to be consecutive in order to function? Otherwise, could we just use the date/timestamp as the build number? It should also address the problem of atomicity.

It might be a bit inelegant, and an abuse of the intended semantics, but I think it's no worse that just using `1` every time and it would certainly be a quick fix for a frustrating problem.

If I understand right it looks like some other people solve this by checking with the scm, e.g. finding the commit number, but this has its own problems, not least portability.

**Comment by pkriens** [comment] 2017-04-05 13:39
Anybody knows how Maven generates this number?

**Comment by rotty3000** [comment] 2017-04-05 14:24
Doesn't it just parse the maven-metadata.xml file to find the next value in
the sequence?

Of course it means it needs to pull the data file down from the target repo.

**Comment by pkriens** [comment] 2017-04-05 14:27
We already need that file anyway, so that sounds like a good idea.

However, what on earth is the purpose of the flag when you can calculate it from the metadata file????

**Comment by eliasvasylenko** [comment] 2017-04-05 15:23
Well, my suggestion probably looks foolish now! For the record incrementing from the previous metadata file was suggested in the email discussion but concerns were raised about atomicity with concurrently running builds, so I was responding to that. I'm sure in practice it will be tolerable though.

**Comment by pkriens** [comment] 2017-04-05 16:37
yes, I think the chance of a collision seems lower than the chance of things not working well today :-)

**Comment by rotty3000** [comment] 2017-04-05 17:46
If multiple actors release snapshots into a remote repository with a high
enough frequency to be concerned with collisions I think there's a problem
with the process of the project!

**Comment by rotty3000** [comment] 2017-05-12 16:13
Please note that I think we have a similar issue with plain installation of snapshots to the local repo. When NOT in offline mode the snapshot is always overwritten when a remote repository contains a snapshot.

You should be able to reproduce simply by:
* build the bnd project locally
* create the most basic maven project with a dependency on the bnd snapshot
* ask maven to print the dependencies (`mvn dependency:tree`)

**Comment by bjhargrave** [comment] 2017-05-15 14:07
Fixed by #2043

**Closed by bjhargrave** 2017-05-15 14:07 UTC
