### ISSUE TITLE
Bnd ArrayIndexOutOfBoundsException with * command on Conditional-Package option

### ISSUE THREAD

**Issue by reyman** [bndtools/bnd#2220] opened 2017-12-03 09:00 UTC
Hi,
I recently reported the issue in goomph which use the latest version of bndtools to declare Manifest : 

When i add `*` option to 'Conditional-Package', i have an error `java.lang.ArrayIndexOutOfBoundsException`

I already report this error in goomph issue tracker : 
https://github.com/diffplug/goomph/issues/40#issuecomment-348743514

The code which report this error is here : https://github.com/ANRGenstar/gamaplugin

**Comment by bjhargrave** [comment] 2017-12-04 14:07
When I cloned the gamaplugin project and ran ./gradlew, I saw the following downloads:

```
Download https://plugins.gradle.org/m2/biz/aQute/bnd/bndlib/2.2.0/bndlib-2.2.0.pom
Download https://plugins.gradle.org/m2/biz/aQute/bnd/parent/2.2.0/parent-2.2.0.pom
Download https://plugins.gradle.org/m2/biz/aQute/bnd/biz.aQute.bndlib/3.2.0/biz.aQute.bndlib-3.2.0.pom
Download https://plugins.gradle.org/m2/biz/aQute/bnd/bndlib/2.2.0/bndlib-2.2.0.jar
Download https://plugins.gradle.org/m2/biz/aQute/bnd/biz.aQute.bndlib/3.2.0/biz.aQute.bndlib-3.2.0.jar
```

So it appears that both bndlib 2.2.0 and bndlib 3.2.0 are BOTH being used which is a source of concern.

And I was able to build the project without seeing any ArrayIndexOutOfBoundsException.

So you need to provide more specific directions on how to reproduce the issue with Bndlib 3.5 which is the current release. The code in this area has change quite significantly since 3.2 and the stacktrace information in your bug is incomplete (it is missing the top lines) and does not fit the current code. 

Even more disturbing is that the stacktrace information does fit the Bndlib 2.2 code: https://github.com/bndtools/bnd/blob/e3dce61619372a2d7eb57c8c239c17f363cc99f6/biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java#L418-L428 which means your problem may be caused by having 2 versions of Bndlib on the gradle plugin classpath since it appears you are in the Bndlib 2.2 code when you get the exception. This could also explain by trying to use Bndlib 3.5 did not address the problem.

I suggest you understand why there are 2 versions of Bndlib present and fix that first. Perhaps some other dependent is pulling in Bndlib 2.2.

**Comment by reyman** [comment] 2017-12-04 16:13
Ok thanks for information, i try to trace the error and i post here if i have news.

**Comment by bjhargrave** [comment] 2017-12-04 22:59
The joys of transitive dependencies...

I will close this issue since the problem is not in Bnd itself.

**Closed by bjhargrave** 2017-12-04 22:59 UTC
