### ISSUE TITLE
java.lang.NoClassDefFoundError: sun/misc/Unsafe while running app in Eclipse

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#3147] opened 2019-04-12 17:41 UTC
When I try to run app in Eclipse:
![image](https://user-images.githubusercontent.com/5578017/56055695-6f76b080-5d5a-11e9-8554-cbc69c8c204d.png)

I get following error:
```
Exception in thread "Camel Thread #0 - LRUCacheFactory" java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at org.apache.camel.com.github.benmanes.caffeine.base.UnsafeAccess.load(UnsafeAccess.java:68)
	at org.apache.camel.com.github.benmanes.caffeine.base.UnsafeAccess.<clinit>(UnsafeAccess.java:42)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BLCHeader$DrainStatusRef.<clinit>(BoundedLocalCache.java:3487)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.camel.com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(Unknown Source)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3043)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3039)
	at org.apache.camel.com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:926)
	at org.apache.camel.util.LRUCache.<init>(LRUCache.java:124)
	at org.apache.camel.util.LRUCache.<init>(LRUCache.java:92)
	at org.apache.camel.util.LRUCache.<init>(LRUCache.java:79)
	at org.apache.camel.util.LRUCache.<init>(LRUCache.java:66)
	at org.apache.camel.util.LRUCacheFactory.newLRUCache(LRUCacheFactory.java:89)
	at org.apache.camel.util.LRUCacheFactory.lambda$warmUp$0(LRUCacheFactory.java:66)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe cannot be found by org.apache.camel.camel-core_2.23.1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
! Failed to start bundle my.service-0.0.1, exception activator error Could not initialize class org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache from: sun.reflect.NativeConstructorAccessorImpl:newInstance0#-2
org.osgi.framework.BundleException: Exception in my.service.Activator.start() of bundle my.service.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:803)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:732)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:584)
	at org.eclipse.osgi.container.Module.start(Module.java:452)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431)
	at aQute.launcher.Launcher.startBundles(Launcher.java:519)
	at aQute.launcher.Launcher.activate(Launcher.java:425)
	at aQute.launcher.Launcher.run(Launcher.java:303)
	at aQute.launcher.Launcher.main(Launcher.java:149)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.camel.com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(Unknown Source)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3043)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3039)
	at org.apache.camel.com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:926)
	at org.apache.camel.util.LRUCache.<init>(LRUCache.java:124)
	at org.apache.camel.util.LRUWeakCache.<init>(LRUWeakCache.java:61)
	at org.apache.camel.util.LRUWeakCache.<init>(LRUWeakCache.java:57)
	at org.apache.camel.util.LRUCacheFactory.newLRUWeakCache(LRUCacheFactory.java:152)
	at org.apache.camel.management.MBeanInfoAssembler.start(MBeanInfoAssembler.java:74)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.management.DefaultManagementMBeanAssembler.doStart(DefaultManagementMBeanAssembler.java:121)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
	at org.apache.camel.management.DefaultManagementAgent.doStart(DefaultManagementAgent.java:395)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.management.DefaultManagementStrategy.doStartManagementStrategy(DefaultManagementStrategy.java:253)
	at org.apache.camel.management.ManagedManagementStrategy.doStart(ManagedManagementStrategy.java:206)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3342)
	at org.apache.camel.impl.DefaultCamelContext$4.call(DefaultCamelContext.java:3248)
	at org.apache.camel.impl.DefaultCamelContext$4.call(DefaultCamelContext.java:3244)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3267)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3244)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3160)
	at my.service.Activator.start(Activator.java:27)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:782)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:775)
	... 10 more
```

But when I do `./gradlew release` and run the bundle in Karaf - everything works just fine!

This is particularly strange since I'm running JDK 8:
![image](https://user-images.githubusercontent.com/5578017/56055843-e9a73500-5d5a-11e9-9be8-0317ef326559.png)

**Comment by bjhargrave** [comment] 2019-04-12 17:46
Bundle's still need to import the packages they needs. Do the proper bundles import `sun.misc`? 

It is possible Karaf has configured the `org.osgi.framework.bootdelegation` system property to include `sun.misc` which is not the default for an OSGi framework and this is why the code runs on Karaf and not in a vanilla OSGi environment.

**Comment by eximius313** [comment] 2019-04-12 17:50
I'm using official camel bundles.
How `org.osgi.framework.bootdelegation` can be configured in bndtools workspace?

**Comment by bjhargrave** [comment] 2019-04-12 17:53
> I'm using official camel bundles.

That does not mean they where built correctly. You should verify if they import `sun.misc` and file a bug report with camel if they use the package and do not import it.

> How `org.osgi.framework.bootdelegation` can be configured in bndtools workspace?

Put the following in the bndrun file:

`-runproperties: org.osgi.framework.bootdelegation="sun.misc"`

**Comment by eximius313** [comment] 2019-04-12 18:01
> `-runproperties: org.osgi.framework.bootdelegation="sun.misc"`
it worked. Where I can find it in documentation?

**Comment by bjhargrave** [comment] 2019-04-12 18:05
In general, search engines are your friend when searching for something. I used google and found:

https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.parentdelegation

Closing issue since there is not a bug in Bndtools. 

In the future, please ask questions like this in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.

**Closed by bjhargrave** 2019-04-12 18:05 UTC

**Comment by eximius313** [comment] 2019-04-12 18:29
I was using search engines, but I was looking for how to solve it in `bnd` not in `OSGi` in general, because Karaf works just fine. Moreover - your link still does not explain how to do parent delegation in `bnd`...

Anyway, for future readers - here is Camel issue: https://issues.apache.org/jira/browse/CAMEL-13415

**Comment by abhaysinghmgr** [comment] 2020-01-09 14:00
Hi @eximius313. You mentioned that it worked for you in Karaf. I am facing the exact issue for the following product versions:
- Karaf 4.2.7
- Camel 2.24.1

I have tried explicitly using `org.osgi.framework.bootdelegation = "sun.misc"` in the karaf/etc/config.properties file without success. Any tips would be appreciated.

**Comment by pkriens** [comment] 2020-01-09 14:03
You likely have a problem with the quotes? Bnd strips those quotes but if your using the properties directly they could confuse the framework.

Kind regards,

	Peter Kriens

**Comment by abhaysinghmgr** [comment] 2020-01-09 14:10
@pkriens I get the same error if I remove the quotes.

**Comment by pkriens** [comment] 2020-01-09 14:11
Was worth a try ... this is an OSGi specified feature. I'm not an export on Karaf and Camel.
