### ISSUE TITLE
Launcher in exported JAR changes all bundle lastModified times every launch

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#4083] opened 2020-05-20 11:51 UTC
I want to use an OSGi framework with a persistent storage folder, so I added the following to my .bndrun file:

```
-runkeep: true
-runstorage: ${.}/.fwdir
```

And then exported it as a standalone JAR using the bnd-export-maven-plugin (version 5.0.1). When running that JAR file with `java -jar`, I noticed that the lastmodified timestamp of every bundle is updated on every launch:

```
$ java -jar app/target/debug.jar
...
g! (bundle 12) getlastmodified
1589974443890
g! stop 0
$ java -jar app/target/debug.jar
...
g! (bundle 12) getlastmodified
1589974474239
```

Note that the timestamp has incremented by approx 3 seconds.

This causes a particular problem when using the OSGi Configurator. Because the bundle containing the configuration resource appears to have been updated, the Configurator re-applies it to Config Admin (this is done irrespective of any Overwrite Policy). Thus we lose all config changes that the user may have made at runtime e.g. using the Felix WebConsole etc.

**Comment by bjhargrave** [comment] 2020-05-20 13:52
I suspect the launcher has no idea if the previously installed bundles are the same as the bundles in the install set. So it must update them, so you get a new lastmodified time (time of update). 

I am not sure how the launcher can reliably know that the previously installed bundles are in fact identical to the bundles in the bundles install set. The Bundle's lastmodified time from asking the framework will be the time they were last installed/updated which is not going to be the same lastmodified time on the jars in the bundle install set.

**Comment by rotty3000** [comment] 2020-05-20 15:32
there's digest checking logic in the launcher and I'm pretty sure that @pkriens had implemented the lazy install which only updated a bundle if digest check failed. See https://github.com/bndtools/bnd/blob/315f1187c2664143d8ed595eb076d950794117fa/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L867

**Comment by rotty3000** [comment] 2020-05-20 15:34
maybe https://github.com/bndtools/bnd/blob/315f1187c2664143d8ed595eb076d950794117fa/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L848 is broken somehow?

**Comment by njbartlett** [comment] 2020-05-20 16:09
Thanks for the hints. I'll hook up a debugger and see what's going on around those lines.

**Comment by pkriens** [comment] 2020-08-25 13:12
I've tested this from several angles and as far as I can see, the digest & minimal update works as intended. E.g. this is the output of a test program:

    # starting in embedded mode
    # not updating jar/com.example.eval.api.jar because identical digest=/sRzjH7GIi3Mir/HCafJ0wWhwic=
    # not updating jar/com.example.eval.rhino.provider.jar because identical digest=QUrn0YjNy8ZwuBGdxDSLS9T26PI=
    # not updating jar/com.example.eval.simple.provider.jar because identical digest=hD0IQtGM2CJMc1BpnrFD+8VV4wk=
    # not updating jar/org.apache.felix.gogo.command-1.1.0.jar because identical digest=CTW4gMjxuzRKiUjiwswNDbzG1hc=
    # not updating jar/org.apache.felix.gogo.runtime-1.1.2.jar because identical digest=rO8olqxAhg8w68UHXEkIB7hTYCU=
    # not updating jar/org.apache.felix.gogo.shell-1.1.2.jar because identical digest=RidB/DXgabCdOgZPpxlJMBZqbj4=
    # not updating jar/org.apache.felix.scr-2.1.16.jar because identical digest=1U2DHdWWRgPBq0vosq3v44ziLCE=
    # not updating jar/rhino-1.7.12.jar because identical digest=FtizcOXdRRPRXuG0tHG5VC68z6E=
    # not updating jar/org.osgi.util.function-1.1.0.jar because identical digest=cPnjTp2ZFkc3hQgxbsSgqRS5FZ8=
    # not updating jar/org.osgi.util.promise-1.1.1.jar because identical digest=+QOUYDGmFHYbkTrcQdVeuMtTpWQ=

    $ java -jar application.bndrun.jar 
    ...
    g! each (bundles) { $it lastmodified }
    0
    1598360286165
    1598360286170
    1598360286174
    1598360286179
    1598360286183
    1598360286187
    1598360286192
    1598360286199
    1598360286213
    1598360286218
    ^C    
    $ java -jar application.bndrun.jar
    ... 
    g! each (bundles) { $it lastmodified }
    0
    1598360286165
    1598360286170
    1598360286174
    1598360286179
    1598360286183
    1598360286187
    1598360286192
    1598360286199
    1598360286213
    1598360286218

So I am closing this as not reproducable.

**Closed by pkriens** 2020-08-25 13:12 UTC
