### ISSUE TITLE
bnd-maven-plugin: Support reproducible builds

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3521] opened 2019-11-03 21:22 UTC
The `Bnd-LastModified` header currently makes a build non-reproducible. If existing the fixed timestamp from `project.build.outputTimestamp` should be used instead (https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318) in the Maven plugin.

**Comment by rotty3000** [comment] 2019-11-03 22:05
couldn't you simply `-removeheaders: Bnd-LastModified`?

**Comment by kwin** [comment] 2019-11-03 22:06
That would be a workaround, this issue is more to make the bnd-maven-plugin in line with the other maven plugins (i.e. evaluate `project.build.outputTimestamp`) and then use its value instead of the current date.

**Comment by rotty3000** [comment] 2019-11-04 05:04
I tried to use that property but maven didn't seem to think it existed.

**Comment by kwin** [comment] 2019-11-04 05:10
You have to explicitly set it. But it is a well known property which is also evaluated by other plugins (m-jar-p, m-source-p). Further details in https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318

**Comment by rotty3000** [comment] 2019-11-04 05:13
Got it, then yeah it should be trivial to check for it.

**Comment by bjhargrave** [comment] 2019-11-04 13:00
BTW, Bnd has options for reproducible builds which Bnd itself uses

https://github.com/bndtools/bnd/blob/a6aed533455f43e8a3802f847e8f6548a868f922/cnf/build.bnd#L58-L59

The latter option removes headers which can vary from build to build like Bnd-LastModified. So if you use these 2 options, you should already be able to make reproducible builds with the maven plugin.

**Comment by bjhargrave** [comment] 2019-11-04 13:40
See also https://maven.apache.org/guides/mini/guide-reproducible-builds.html which is new to `maven-jar-plugin` for the just released 3.2.0. But the use of `project.build.outputTimestamp` documented there is to use a fixed value rather than the actual current build time.

For the `bnd-maven-plugin`, if we see `-reproducible: true` in the Bnd configuration, we should then set the maven `project.build.outputTimestamp` to the fixed time stamp we use for Bnd reproducible builds. 

https://github.com/bndtools/bnd/blob/a6aed533455f43e8a3802f847e8f6548a868f922/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java#L71-L87

Note: We should not be setting `Bnd-LastModified` to the value of `project.build.outputTimestamp`  since that would be a lie. If the user does not want that header, they can either `-removeheaders` it or, better yet, use `-noextraheaders: true `.

**Comment by rotty3000** [comment] 2019-11-04 15:30
The `bnd-maven-plugin` is a subordinate in the maven build and so I don't think _setting_ `project.build.outputTimestamp` would have the desired effect. The goal at most here would be for `bnd-maven-plugin` to read some signature flags from maven and maybe react by turning on it's reproducible build features.

**Comment by bjhargrave** [comment] 2019-11-04 15:32
I guess bnd-maven-plugin could see if that project property is set, and if so, enable `-reproducible: true` and `-noextraheaders: true ` for the Builder.

**Comment by rotty3000** [comment] 2019-11-04 15:36
That's what I'm thinking. @kwin since you know more about this, could you confirm that `project.build.outputTimestamp` is really the best _signature_ for us to look for?

**Comment by kwin** [comment] 2019-11-04 17:27
No, you should rather introduce a dedicated parameter similar like what maven-jar-plugin (https://github.com/apache/maven-jar-plugin/blob/e036eb2a511c6771c172b23d9d33c5563f1d7ae2/src/main/java/org/apache/maven/plugins/jar/AbstractJarMojo.java#L151) does. I am not sure if relying on a fixed timestamp is better or whether a boolean flag would actually be enough (to completely leave out the non-fixed headers). Maybe a dedicated boolean Maven plugin parameter which by default is set to true if `project.build.outputTimestamp` is set to something sounds reasonable to me. WDYT?

**Comment by bjhargrave** [comment] 2019-11-04 17:33
Since bnd-maven-plugin does not jar the bundle, there is no point in defining any new configuration for this. We would need to "look" into the configuration of maven-jar-plugin to see if it is has the `outputTimeStamp` property set to something which seems wrong.

The only thing that really needs to be done for bnd-maven-plugin is to not emit manifest headers which depend upon the build time. `-noextraheaders: true` should do this. 

But it seems wrong to add a configuration property to bnd-maven-plugin which is the duplicate of the maven-jar-plugin `outputTimeStamp` property especially since bnd-maven-plugin does not even make the jar so it does not control the timestamps of the jar entries.

**Comment by bjhargrave** [comment] 2019-11-15 17:05
Closing since there is no change to the plugin. Use Bnd config for `-noextraheaders: true` if you want reproducible builds with maven.

**Closed by bjhargrave** 2019-11-15 17:05 UTC

**Comment by rombert** [comment] 2020-01-09 15:36
Testing with `-noextraheaders: true` shows that reproducible builds do not yet work completely. The single difference for us is the `Bundle-Version` header. Between two invocations I get a difference such as:

```$ diff -ur 1/META-INF/MANIFEST.MF 2/META-INF/MANIFEST.MF
--- 1/META-INF/MANIFEST.MF	2019-10-02 08:04:00.000000000 +0200
+++ 2/META-INF/MANIFEST.MF	2019-10-02 08:04:00.000000000 +0200
@@ -28,7 +28,7 @@
  itbox.apache.org/repos/asf/sling-org-apache-sling-api.git",tag=HEAD
 Bundle-SymbolicName: org.apache.sling.api
 Bundle-Vendor: The Apache Software Foundation
-Bundle-Version: 2.22.1.20200109153228096
+Bundle-Version: 2.22.1.20200109153234609
 Export-Package: org.apache.sling.api;version="2.3.4";uses:="javax.servle
  t,javax.servlet.http,org.apache.sling.api.adapter,org.apache.sling.api.
  request,org.apache.sling.api.resource",org.apache.sling.api.adapter;ver
```

To reproduce, you can run the `test.sh` script from https://github.com/apache/sling-org-apache-sling-api/tree/feature/reproducible-builds ( but note that it needs a parent pom that is not yet release, so you may want to wait for a couple of days ). However, the cause of the error should be clear.

**Comment by bjhargrave** [comment] 2020-01-09 18:40
This is caused by an odd historical behavior of bnd-maven-plugin. If `Bundle-Version` is not explicitly set _and_ if the `-snapshot` instruction is not also set in the Bnd configuration, then the bnd-maven-plugin will set `-snapshot: ${tstamp}` into the Bnd configuration. 

https://github.com/bndtools/bnd/blob/5a777f9383a8b4b667945f5e8f47a4d833a965e9/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java#L305-L307

This will cause the `SNAPSHOT` qualifier in `Bundle-Version` to be replaced with the timestamp value.

https://github.com/bndtools/bnd/blob/5a777f9383a8b4b667945f5e8f47a4d833a965e9/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L439-L465

So you will also need to set `-snapshot: SNAPSHOT` in the Bnd configuration to prevent the above behavior.

**Comment by bjhargrave** [comment] 2020-01-09 19:56
See https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#reproducible-builds where I added a section to the bnd-maven-plugin readme.

**Comment by kwin** [comment] 2020-01-09 21:21
@bjhargrave Thanks a lot for the clarification and for the documentation update.

**Comment by rombert** [comment] 2020-01-10 09:21
That makes sense, thanks @bjhargrave

**Comment by kwin** [comment] 2020-09-06 21:22
Just for the record: Since https://github.com/bndtools/bnd/commit/32a6357d173ec08a6d96ada9415d38464fbbc715 reproducible builds are automatically enabled once project.build.timestamp is set
