### ISSUE TITLE
Range macro with implicit version parameter on Import-Package statement generates false warning

### ISSUE THREAD

**Issue by jonathanvila** [bndtools/bnd#1368] opened 2016-03-28 18:50 UTC
When I use this expression in my maven-bundle-plugin configuration :
_<Import-Package>com.mypackage.base*;version="$&lt;range;[==,=+)&gt;"</Import-Package>_

It always complain with :
_ No translation found for macro: range;[==,=+)_

If I put an explicit version in the range macro : _version="$&lt;range;[==,=+);1.0&gt;"_ then it works but with that value not with the dependency version.

**Comment by bjhargrave** [comment] 2016-04-01 21:42
It seems the `${@}` macro is not set. Can you provide more details on the complete configuration?

**Comment by jonathanvila** [comment] 2016-04-03 07:06
Hello

What do you mean?  I thought that the {@} was something created and set by
the plug-in.

Which details do you need? I don't know what else to send

**Comment by bjhargrave** [comment] 2016-04-05 14:16
The details needed are how to reproduce the problem.

Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by jonathanvila** [comment] 2016-04-05 21:22
Can you use that macro in the plugin ? is it working for you ?

We only have a POM with an Import-Package macro.... Obviously I can not put
my company's project in github as it's not OSS.

<Import-Package>com.mypackage.base*;version="$&lt;range;[==,=+)&gt;",
*</Import-Package>
Always complain with :

 No translation found for macro: range;[==,=+)

But if I put the second argument to the macro :
version="$&lt;range;[==,=+);1.0&gt;" then it works but it puts [1.0, 1.1)
in my MANIFEST, and what I want is that it puts the version defined in the
dependency section in the pom, something like [4.0, 4.1)

I'm using version 3.0.0 of the plugin, but I've tried with previous
versions also.
I've also tried using CDATA :

<Import-Package><![CDATA[com.mypackage.base*;version="$<range;[==,=+)>",*]]></Import-Package>

But I get the same result.

If I use the policy it works great, but with all the packages, and what I
want is to restric this policy to a concrete package :

           <_consumer-policy>$&lt;range;[==,=+)></_consumer-policy>

Best



[image: Inline image 2]

* Jonathan Vila    ** <https://www.twitter.com/jonathan_vila>
<http://www.linkedin.com/in/jonathanvila>*

* jonathan.vila@gmail.com <jonathan.vila@gmail.com>*

**Comment by bjhargrave** [comment] 2016-04-05 22:04
I used the latest build of the bnd-maven-plugin and the following worked fine for me:

```
Import-Package: org.example.types*;version="$<range;[==,=+)>", *
```

This was in a CDATA section of the `<bnd>` element of the pom. It generated the expected version range on the import but did generate the warning message:

```
[WARNING] /Users/hargrave/git/bnd/maven/bnd-maven-plugin/target/integration-test/projects/test/test-api-bundle/pom.xml [0:0]: No translation found for macro: range;[==,=+)
```

Note sure why the warning is produced, but the manifest was correct. So it seems to work properly but produce a pointless warning message.

**Comment by bjhargrave** [comment] 2016-04-05 22:09
BTW, I think you can get the version range behavior you want my marking the package as `@ProviderType`. That can be done in the package-info.java file for the package. You can also do:

```
<Import-Package>com.mypackage.base*;provide:=true, *</Import-Package>
```

in the pom.

**Comment by bjhargrave** [comment] 2016-04-05 22:57
The warning is caused by <https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L291> which gets the `Import-Package` header when the `${@}` macro is not set.

Obviously people will want to use macros in their `Import-Package` header but this line should not result in the warning about an invalid use of the `${range}` macro. @pkriens how do we prevent this warning? Basically we want to leave the `${range}` macro unprocessed here, so it can be processing in context later, but process other macros that may be used in the `Import-Package` header.

**Comment by pkriens** [comment] 2016-04-06 11:03
I guess we can get the raw property, it is just a check to see if it is set so a default can be used.

**Comment by bjhargrave** [comment] 2016-04-06 12:24
I think it is more complicated than that since I might use some macros to create the header value:

```
eclipse-pkgs: org.eclipse.*;version="${range;[==,=+)}"
osgi-pkgs: org.osgi.*;version="${range;[==,++)}"
Import-Package: ${eclipse-pkgs},${osgi-pkgs},*
```

So we need to do the macro expansion when we get the `Import-Package` header but defer the expansion of the `range` macro til we are processing each imported package since it relies upon `${@}` being set to the imported package version.

**Comment by pkriens** [comment] 2016-04-06 12:36
But the line you indicate the only thing that is relevant if there is ANY content. Even a macro is content when raw.

**Comment by bjhargrave** [comment] 2016-04-06 12:43
But 7 lines later, <https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L298>, it creates an Instruction from that value, so any macros will have needed expansion.

**Comment by pkriens** [comment] 2016-04-06 13:05
That is true. Ok, maybe we could let the range macro detect that one of the arguments has a context macro. if so, it should return itself? This make it expand later

**Comment by bjhargrave** [comment] 2016-04-06 13:07
That would work. So if no 3rd argument and no `${@}` macro, then return itself rather than null which triggers the warning?

**Comment by bjhargrave** [comment] 2016-04-07 12:56
Fixed by https://github.com/bndtools/bnd/commit/7cdf0a6bbc4a82ee8b8a4e283d381cc7d98dbf7e

**Closed by bjhargrave** 2016-04-07 12:56 UTC
