### ISSUE TITLE
bndtools fails to parse class with lambda functions

### ISSUE THREAD

**Issue by jhanders34** [bndtools/bnd#3239] opened 2019-06-12 01:17 UTC
Per @bjhargrave I am opening an issue against bndtools as discussed in [this open liberty pull request](https://github.com/OpenLiberty/open-liberty/pull/7857)

The following smallrye code fails to parse in bndtools.  The pull request updates the code in a way that allows bndtools to proceed.  The updated code lines up with other code in the class.

```
  private <T> void produceIndividualPayloads() {
    setPublisher(ReactiveStreams.<T>generate(this::invoke)
      .map(Message::of));
  }

  private void produceIndividualCompletionStageOfMessages() {
    setPublisher(ReactiveStreams.<CompletionStage<Message>>generate(this::invoke)
      .flatMapCompletionStage(Function.identity()));
  }

  private <P> void produceIndividualCompletionStageOfPayloads() {
    setPublisher(ReactiveStreams.<CompletionStage<P>>generate(this::invoke)
      .flatMapCompletionStage(Function.identity())
      .map(Message::of));
  }
```

The main issue is the this::invoke.  Changing that as is done in the pull request makes bndtools happy.  The errors that you will get depends on if the method is updated or not.  The error for each of the respective methods you will get is:

Exception: java.lang.IllegalArgumentException: invalid signature: +TT;

Exception: java.lang.IllegalArgumentException: invalid signature: +Ljava/util/concurrent/CompletionStage<Lorg/eclipse/microprofile/reactive/messaging/Message;>;

Exception: java.lang.IllegalArgumentException: invalid signature: +Ljava/util/concurrent/CompletionStage<TP;>;

The rest of the stack is as below:

	at aQute.bnd.signatures.Signatures.parseReferenceTypeSignature(Signatures.java:63)
	at aQute.bnd.signatures.Signatures.parseJavaTypeSignature(Signatures.java:48)
	at aQute.bnd.signatures.MethodSignature.parseResult(MethodSignature.java:131)
	at aQute.bnd.signatures.MethodSignature.parseMethodSignature(MethodSignature.java:113)
	at aQute.bnd.signatures.MethodSignature.of(MethodSignature.java:26)
	at aQute.bnd.osgi.Descriptors$$Lambda$641.000000002853E410.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1138)
	at aQute.bnd.osgi.Descriptors.getMethodSignature(Descriptors.java:484)
	at aQute.bnd.osgi.Analyzer.getMethodSignature(Analyzer.java:3135)
	at aQute.bnd.osgi.Clazz.processSignature(Clazz.java:1114)
	at aQute.bnd.osgi.Clazz.processAttributes(Clazz.java:994)
	at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:868)
	at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:776)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:764)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:754)
	at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2608)
	at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2513)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:204)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:408)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:909)
	at aQute.bnd.osgi.Builder.build(Builder.java:118)
	at aQute.bnd.osgi.Builder.builds(Builder.java:1400)
	at aQute.bnd.build.ProjectBuilder.builds(ProjectBuilder.java:642)
	at aQute.bnd.build.Project.buildLocal(Project.java:1862)
	at aQute.bnd.build.Project.build(Project.java:1676)
	at aQute.bnd.build.Project.build(Project.java:2303)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:244)
	at org.bndtools.builder.BndtoolsBuilder$$Lambda$613.000000002825F010.call(Unknown Source)
	at bndtools.central.Central.bndCall(Central.java:676)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:124)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

You can easily reproduce this problem by undoing the aforementioned open liberty pull request.  It has not been merged yet, but will be soon.

I am using the latest publicly available bndtools 4.2.0.

**Comment by bjhargrave** [comment] 2019-06-12 14:35
This appears to be a bug in the Eclipse Compiler for Java (ECJ)  and not a bug in Bnd. When compiled with javac, this issue does not present.

Bnd is parsing the result for a generic method signature (`aQute.bnd.signatures.MethodSignature.parseResult`). Per the JVMS (https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-MethodSignature), the result (return type) of a `MethodSignature` (https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-Result) must be `V` (void) or a `JavaTypeSignature` (https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-JavaTypeSignature). A `JavaTypeSignature` must be one of the `BaseTypes` (B C D F I J S Z) or a `ReferenceTypeSignature` (https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-ReferenceTypeSignature). A `ReferenceTypeSignature` must start with either 'L' (which is a `ClassTypeSignature`), `T` (which is a `TypeVariableSignature`), or `[` (which is an `ArrayTypeSignature`).

It is not permitted to start with `+` which appears to be a `TypeArgument`  (https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-TypeArgument).

In looking at the generated class file from ECJ with javap, you can see that ECJ emits invalid generic method signatures on the generated (synthetic) lambda functions. The method's descriptors are correct. These methods should not even have generic method signatures. At runtime, I imagine no one cares about the generic method signatures for these synthetic methods. But tools, like Bnd, will complain when they encounter such invalid signatures. 

```
  private ? extends T lambda$8();
    descriptor: ()Ljava/lang/Object;
    flags: ACC_PRIVATE, ACC_SYNTHETIC
    Signature: #245                         // ()+TT;
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: iconst_0
         2: anewarray     #133                // class java/lang/Object
         5: invokevirtual #135                // Method invoke:([Ljava/lang/Object;)Ljava/lang/Object;
         8: areturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       9     0  this   Lio/smallrye/reactive/messaging/PublisherMediator;

  private ? extends java.util.concurrent.CompletionStage<org.eclipse.microprofile.reactive.messaging.Message> lambda$9();
    descriptor: ()Ljava/util/concurrent/CompletionStage;
    flags: ACC_PRIVATE, ACC_SYNTHETIC
    Signature: #248                         // ()+Ljava/util/concurrent/CompletionStage<Lorg/eclipse/microprofile/reactive/messaging/Message;>;
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: iconst_0
         2: anewarray     #133                // class java/lang/Object
         5: invokevirtual #135                // Method invoke:([Ljava/lang/Object;)Ljava/lang/Object;
         8: checkcast     #249                // class java/util/concurrent/CompletionStage
        11: areturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      12     0  this   Lio/smallrye/reactive/messaging/PublisherMediator;

  private ? extends java.util.concurrent.CompletionStage<P> lambda$10();
    descriptor: ()Ljava/util/concurrent/CompletionStage;
    flags: ACC_PRIVATE, ACC_SYNTHETIC
    Signature: #252                         // ()+Ljava/util/concurrent/CompletionStage<TP;>;
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: iconst_0
         2: anewarray     #133                // class java/lang/Object
         5: invokevirtual #135                // Method invoke:([Ljava/lang/Object;)Ljava/lang/Object;
         8: checkcast     #249                // class java/util/concurrent/CompletionStage
        11: areturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      12     0  this   Lio/smallrye/reactive/messaging/PublisherMediator;
```

While javap strangely converts the invalid method signatures into pseudo-source code, I can find no allowance in the JVMS to support these method signatures.

The only change I could see making to Bnd here is to have Bnd ignore generic signatures on synthetic elements.

This should be reported to Eclipse as a defect in ECJ.

**Comment by bjhargrave** [comment] 2019-06-12 19:42
Closing since this is a defect in ECJ and since I made a change to Bnd to not process signatures on synthetic elements.

Thanks for reporting this to Bnd.

**Closed by bjhargrave** 2019-06-12 19:42 UTC
