### ISSUE TITLE
Eclipse will completely crash and die if the jar viewer is open while the artifact is rebuilt by m2e

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3511] opened 2019-10-30 13:50 UTC
Steps to reproduce:
- load a maven project using bndtools.m2e
- open target folder and view the artifact using the bndtools jar viewer
- go to the `print` tab (bottom left corner of jar viewer)
- make a significant change (like adding any package from the classpath not in the bundle sources):
  ```
  Export-Package: org.osgi.framework.*,*
  ```

Results in:
```
!ENTRY org.eclipse.ui 4 0 2019-10-30 09:48:38.178
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at bndtools.jareditor.internal.JARPrintPage.refresh(JARPrintPage.java:57)
	at bndtools.jareditor.internal.JAREditor.lambda$updateContent$0(JAREditor.java:87)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4857)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4409)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```

**Eclipse**
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
**Bndtools**
4.4.0.DEV-201910271912-gbdc69a9	bndtools.main.feature

**Comment by bjhargrave** [comment] 2019-11-15 17:08
Note: This works fine on Bnd workspace builds.

**Comment by bjhargrave** [comment] 2020-01-24 16:23
@rotty3000 Please verify if this is still a problem with the new JarEditor.

**Comment by bjhargrave** [comment] 2020-04-14 12:19
Closing since there has been no feedback confirming this is still an issue with the new JarEditor. Please reopen if it is confirmed to still be an issue.

**Closed by bjhargrave** 2020-04-14 12:19 UTC
