### ISSUE TITLE
To represent fragments in the Junit5 test plan heirarchy, or not!

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3673] opened 2019-12-18 16:23 UTC
Currently in the Junit5 support, fragments are modeled. I wonder if this the right thing to do. Currently associated issues are:
- deep tree in the Eclipse Junit5 view
- double execution of tests when making a test selection (non-auto case)

**Comment by rotty3000** [comment] 2019-12-18 16:32
We don't have hierarchy using the original tester and I've never heard anyone complain about it.
![Screenshot from 2019-12-18 11-26-49](https://user-images.githubusercontent.com/146764/71104169-62cc1700-2189-11ea-88b3-bac74bae2c39.png)

When I make a selection, I really don't care about the hierarchy
![Screenshot from 2019-12-18 11-28-09](https://user-images.githubusercontent.com/146764/71104241-81321280-2189-11ea-94a7-efe35605167b.png)

Currently I get this:
![Screenshot from 2019-12-18 11-29-25](https://user-images.githubusercontent.com/146764/71104420-c0606380-2189-11ea-8883-5fe92b06cbe8.png)
To be honest why do I even need the hierarchy because when I click any of the tests I am taken directly to it. So I'm not sure I see the value. I care about if the tests passed or failed, how to get to them but not so much about the (in my mind superfluous) details provided by the hierarchy.

**Comment by rotty3000** [comment] 2019-12-18 16:35
I understand there is a duplication bug here, but I don't see any benefit to representing the fragment as a node which doesn't appear to happen in the auto mode anyway, so why in selection mode?

**Comment by rotty3000** [comment] 2019-12-18 16:38
I think I would be ok if we just never considered fragments at all (simply ensure that they bind to a host bundle so that the Test-Cases header is observable on the host and that's it.)

**Comment by kriegfrj** [comment] 2019-12-19 03:04
> We don't have hierarchy using the original tester and I've never heard anyone complain about it.

Well, I never heard anyone complain about not having a cell phone 30 years ago. And when they eventually became available, many people complained about them and didn't want them. Now it is hard to find people who complain (though admittedly not impossible 😉 ) New technology brings new possibilities which can eventually become new expectations. :smile:

I guess what I'm saying is, while I'm open to having a discussion about whether or not the hierarchy should stay or go, I think that the fact that no one complained about it in the past is not in itself proof that the feature is not good or necessary.

I did float this as a new feature for discussion when I first submitted the PR in April, as I knew it was a significant departure from the original tester. I'm glad that now that people have had a chance to use it in anger they are in a better position to appreciate it (for better or worse), so it's probably a good time to have this discussion.

> Currently with Junit5 I get this in auto mode:
> And this when selecting a test case:
>

Note that things have changed a bit, in particular with the fix in #3667. Also note that your screenshots are not a strict apples-to-apples comparison as the JUnit 5 one included failing tests (which caused the hierarchy to display expanded by default). Here are some equivalent screenshots with the fix in #3667 included:

Auto mode:
![JUnit5AllPassing](https://user-images.githubusercontent.com/7224087/71139220-78ab0c00-225d-11ea-9a5b-407df3bab650.png)

Single test:
![JUnit5Single](https://user-images.githubusercontent.com/7224087/71139231-85c7fb00-225d-11ea-95de-28226e9bbdad.png)

Note that the duplicated test from the fragment bundle in the single test mode is gone.

> To be honest why do I even need the hierarchy because when I click any of the tests I am taken directly to it. So I'm not sure I see the value. I care about if the tests passed or failed, how to get to them but not so much about the (in my mind superfluous) details provided by the hierarchy.

As with any arrangement of data, the hierarchy becomes more valuable as the number of data points increases.

The hierarchy is possibly superfluous in your case because you're only running a handful of test classes, and furthermore they are all in the same fragment, which is attached to the same bundle. Under such circumstances, I can accept the argument that the hierarchy is superfluous. In fact, you could go further and say when you're only running a single test method then displaying the test class is superfluous!

But if the system-under-test is more complicated, the extra nodes in the hierarchy could be more useful to you. For example, if you had multiple test bundles, or a bundle with multiple fragments. It may also be useful to know at a glance which bundle your fragment attached to.

My proposal (which I mentioned way back in #3145) is to go through the test plan at the end and remove any nodes in the hierarchy that have no siblings, to the depth of the engine node (below that the other engines are responsible for the hierarchy). That way the extra nodes in the hierarchy will only appear when you need them to disambiguate.

> I understand there is a duplication bug here, but I don't see any benefit to representing the fragment as a node which doesn't appear to happen in the auto mode anyway, so why in selection mode?

It *should* happen in auto mode too, if it's working as designed (see my screenshot above). And also as noted above, the duplication bug is now fixed. I think that the missing node in auto-mode was actually an alternative manifestation of the same bug fixed in #3667.

**Comment by kriegfrj** [comment] 2019-12-19 03:08
> To be honest why do I even need the hierarchy because when I click any of the tests I am taken directly to it.

I forgot to add: this "click on the test and get taken directly to it" doesn't work for tests from bundles outside the current project. Eg, if you're running a test scenario with two test bundles (each from different test projects). It is possible that this could be fixed.

**Comment by bjhargrave** [comment] 2020-01-10 16:12
Lets leave things as they are (hierarchy) for 5.0. If we get push back from users of 5.0, we can make UI improvements in 5.1.

**Comment by kriegfrj** [comment] 2020-01-13 04:36
Do you think we should bring this to people's attention on the bndtools-users mailing list so that they can keep an eye on it and and their feedback here?

**Comment by bjhargrave** [comment] 2020-01-13 14:34
Sure. Once 5.0 is released, you should send an email to the list to solicit feedback.

**Comment by bjhargrave** [comment] 2020-04-14 12:18
I have seen no comments on this topic. Perhaps we can close this issue?

**Closed** 2020-04-17 15:47 UTC
