### ISSUE TITLE
ComponentProperty with class value produces a buildloop

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2716] opened 2018-11-09 10:00 UTC
```java
@ComponentPropertyType
public @interface MyProp {

    public Class[] value() default {Object.class};
} 
```
Using the Annotation without a given value works fine and produces something like this:
<property name="my.prop" type="String">java.lang.Object</property> 

The moment I add a add a value like ```@MyProp(TestInterface.class)``` bndtools goes into a build loop and states the following problem while doing so: "Invalid data type ConcreteRef". 

BND Version 4.1.0

**Comment by timothyjward** [comment] 2018-11-09 10:36
This is a duplicate of #2698 and affects Component Property Types using `Class[]` as a value type. `Class` and `String[]` both work fine as a workaround, or you can use the 4.2.0.DEV stream which is already fixed.

**Closed by timothyjward** 2018-11-09 10:36 UTC
