### ISSUE TITLE
Closed projects are still visible in Repositories view

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#2963] opened 2019-02-12 12:03 UTC
Closed projects should not be visible anymore, but they are:
![image](https://user-images.githubusercontent.com/5578017/52634094-946bb600-2ec6-11e9-9af4-ba2e5c56bc2b.png)

**Comment by bjhargrave** [comment] 2019-02-12 13:49
Bndtools is a set of Eclipse plugins which can provide a view over the Bnd workspace on the file system. The Bnd workspace on the file system is managed by the bndlib code library which is generally unaware of Eclipse.

So closing a project in Eclipse does not mean anything to bndlib. Those projects are still on the file system and may be dependencies of other projects which can remain open in Eclipse. 

The Repositories view is a view of the repositories known to the Bnd workspace and include projects in the Bnd workspace. Since bndlib manages this and is unaware of Eclipse and closed projects, it reports all known projects.

That said, I guess the Repository view could attempt to no show workspace projects which are closed in Eclipse, but that seems not much value.

In closing, there is little to no value in closing Bnd projects in Eclipse since the projects still exist in the Bnd workspace on the file system and bndlib still cares about them.

**Comment by eximius313** [comment] 2019-02-12 13:52
So why when you close just one of the projects, then another claims that are unresolved dependencies?
![image](https://user-images.githubusercontent.com/5578017/52639962-c2a4c200-2ed5-11e9-8c2b-304b2b7787ce.png)
![image](https://user-images.githubusercontent.com/5578017/52640003-d7815580-2ed5-11e9-83fc-c541603c6a53.png)

**Comment by bjhargrave** [comment] 2019-02-12 13:55
Because the Bndtools builder is an Eclipse incremental builder. It used the bndlib code to build the bundle but Bndtools is driving bndlib (much like maven would drive the bnd-maven-plugin for a maven build and gradle would drive the bnd gradle plugin for a gradle build). Since you closed a project, the Bndtools incremental builder cannot operate on it any longer and if the project is a dependency of an open project, you will see problems.

**Comment by eximius313** [comment] 2019-02-12 14:06
Ok, so you're saying that

> So closing a project in Eclipse does not mean anything to bndlib

and

>Since bndlib manages this and is unaware of Eclipse and closed projects

but 

> Bndtools builder is an Eclipse incremental builder. It used the bndlib code to build the bundle but Bndtools is driving bndlib

So Bndtools builder communitate with bndlib somehow...

I just find this behavior inconsistent, but if your will is to close this issue, then I'm fine with it.

**Comment by bjhargrave** [comment] 2019-02-12 14:10
I am just trying to explain the way things are and have been for some time. 

Bndtools is not a pure Eclipse story. It is built on top of bndlib which must support Bndtools, maven, gradle, ant, ... 

Eclipse, as an IDE, is challenging since things change during use unlike a command line build.

Making Bndtools/bndlib work better in Eclipse would be great. But I think it is a lot of work and not of personal interest to me. It will take someone to invest the time in a series of PRs to add better support.

**Comment by pkriens** [comment] 2019-02-12 14:16
The problem is that we try to mimic the CI build through gradle/ant/sbt/etc as close as possible. We can therefore not use any Eclipse specific metadata since there is no way to get that from gradle et. al.

If you want to disable a bnd project, you can add 

	-nobundle: true

This will not build the jar. If you do not want to do this per project, you can do this via macros.

Kind regards,

	Peter Kriens

**Comment by rotty3000** [comment] 2019-02-12 15:02
**Bnd Workspace** model is not merely an _archetype_ for gradle projects. It is an opinionated project model with a strict structure.

What you probably expected to find was more, like what @bjhargrave suggested, what we've dubbed **non-workspace gradle plugins** [1]. These can be used with pure gradle (multi-module) projects and if desired you can use tooling like Eclipse Build-Ship to manage them. What's more is that you _CAN_ use the bndtools bnd editor for editing bnd/bndrun files in this model. However, the integration will not be as tight as you see with the Bnd Workspace.

[1] https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#gradle-plugin-for-non-bnd-workspace-builds

**Comment by eximius313** [comment] 2019-02-12 15:24
@rotty3000 this is exactly the issue I had here https://github.com/bndtools/bnd/issues/2962
1) I have Gradle multiproject build
2) I used:
```
plugins {
  id "biz.aQute.bnd.builder" version "4.1.0" apply false
}
``` 
3) `./gradlew jar` created budle jars properly
4) And I even managed to add `Bndtools Project Nature`:
![image](https://user-images.githubusercontent.com/5578017/52646115-7a3fd100-2ee2-11e9-9547-d693ca9099d2.png)

but as you can see it is not available in Repositories view :(

**Comment by rotty3000** [comment] 2019-02-12 15:42
Yeah, adding the Bndtools Project Nature is not going to work in your scenario. It should _probably_ be called **Bnd Workspace Project Nature** to clarify where it can be used.

However, you don't need the nature at all to use the editors. But like I said, the integration will be weak. 

Also `bndrun`'s should be configured as `-standalone: <an/index/file>` (where the index file comes form the bnd gradle index task`
**OR**
`-standalone: true` PLUS `-plugin: <repo.definitions>`

**Comment by eximius313** [comment] 2019-02-12 15:52
@rotty3000, thanks - I'll check this

**Comment by eximius313** [comment] 2019-02-12 16:54
@rotty3000 
>It should _probably_ be called **Bnd Workspace Project Nature** to clarify where it can be used.

I've tested this on vanilla java projects and it works just fine

>you don't need the nature at all to use the editors

apparently when I don't add project nature:
1) It's not visible in repositories thus it can not be user as a dependency
2) `bnd.bnd` is not being created

So it seems that I must add the nature if I want to use the workspace.

**Comment by bjhargrave** [comment] 2019-02-12 18:02
I am going to close this bug. Someone can submit PRs if they wish to make Bndtools better with respect to projects closed in Eclipse.

**Closed by bjhargrave** 2019-02-12 18:02 UTC
