### ISSUE TITLE
BND tools does not take care import package of classes referred in annotation

### ISSUE THREAD

**Issue by nfalco79** [bndtools/bnd#2810] opened 2018-12-12 15:29 UTC
BND does not compute annotation field of type class that means the Import-Package is missing of those classes referred in annotations.

Example (bundle A):
```
package model;

import model.l10n.adapter.L10NValuesDTOXmlAdapter;

@XmlRootElement
public abstract class AbstractDTO {
    @XmlJavaTypeAdapter(value = model.l10n.adapter.L10NValuesDTOXmlAdapter.class)
    protected Set<LocalizedValueDTO> getL10nValues() {
    }
}
```

bundle B depends on bundle A
```
package core;

import model.AbstractDTO;

@XmlRootElement
public abstract class MyDTO extends AbstractDTO {
}
```

The produced manifest has contains model pacakge but miss of model.l10n.adapter pacaklge referred in XmlJavaTypeAdapter annotation field.
I see issue #120 and the annotation is runtime.
```
@Retention(RUNTIME) @Target({PACKAGE,FIELD,METHOD,TYPE,PARAMETER})
public @interface XmlJavaTypeAdapter {
```

**Comment by bjhargrave** [comment] 2018-12-12 16:07
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

Also, you fail to mention anything about what version of Bnd you are using. But a small github repo, as requested above, will answer that.

**Comment by bjhargrave** [comment] 2018-12-12 16:11
In looking at your code snippets, I don't see that bundle B has any reference to a type in the `model.l10n.adapter` package. Bundle A has such a reference. So I don't see any reason why Bnd should have bundle B import the `model.l10n.adapter` package.

**Comment by nfalco79** [comment] 2018-12-12 17:18
we use the latest bnd maven plugin 4.1.0.
If not `model.l10n.adapter` is in the import package at runtime when is de/serialized goes in exception bacase could not load the class referred in the annotation.

**Comment by bjhargrave** [comment] 2018-12-12 18:17
Yes, but it is the AbstractDTO type in bundle A that references the package. If bundle B needs access to the package, there is no way for Bnd to know that. I don't think it is reasonable for Bnd to make bundle B import and package referenced by any RUNTIME annotation in any super type/ super inteface of a type. Bnd already imports the packages of the direct super type and direct super interfaces. 

You are suggesting Bnd must also analyze the direct super type and its super types (and the direct super interfaces and their super interfaces) for RUNTIME annotation use and import any the packages of any type references found in that hierarchy. That would be quite a large change and create a much larger package dependency chain.

The issue is in the serializer in that it should use the class loader of the type it is inspecting for annotations to load those annotations and not assume that the class loader of the sub type has visibility to all annotations of the super type/super interface hierarchy.  Most serializers assume a flat class loader.

Note: this same issue will be present in JPMS unless the module holding a type referenced in the RUNTIME annotation opens itself to any module holding the sub type. It is not likely that the module holding a type referenced in the RUNTIME annotation will know in advance it has to open itself to all other modules.

**Comment by pkriens** [comment] 2018-12-13 14:42
Aren't custom validators being passed as a class object? 

If they are passed as a name then you're just screwed. In OSGi each class is identified by a class loader and a class so there is no possible way you can find the class correctly.

Once you have a class object, or some reflective member, you can always find the proper class (loader) with almost no effort. The only problem is really only when all you have is a name.

**Comment by nfalco79** [comment] 2018-12-20 11:05
yes is passed as class object.

Other case is javax.inject. There is a custom annotation Foo annotated @Qualifier in a bundle A, the bundle B annotate own class with @Foo but sisu does not work because if the bundle does not import javax.inject it is skipped.

**Comment by rotty3000** [comment] 2018-12-20 17:46
I've experimented with Aries CDI which uses bnd for all OSGi packaging, including the analysis required for CDI bundles.

Here's an example of a bundle containing a single class that has an annotation (`@Service`) which is meta-annotated with `@Qualifier` (the only reference to `javax.inject` in the bundle):
https://github.com/apache/aries/blob/trunk/cdi/cdi-itests/src/main/java/org/apache/aries/cdi/test/tb2/PojoImpl.java

You'll also note that the manifest generated for this bundle only contains the following imports:
```
Import-Package: org.apache.aries.cdi.test.interfaces;version="[0.0,1)"
 ,org.osgi.service.cdi.annotations;version="[1.0,2)"
```

Meanwhile, when the CDI impl (JBoss Weld in this case) processes this bundle, it easily identifies the `@Service` annotation as being a qualifier without the need for the client bundle to import the package.

I believe it is essential, as @bjhargrave and @pkriens point out, that the JVM's loose coupling of annotations be upheld in OSGi packaging model.

After some consultation, I believe the logical conclusion is that the annotation processing engine has to be the responsible for handling this loose coupling using something similar to the following approach:
```
ClassLoader annoLoader = annotation.annotationType().getClassLoader();
Class<? extends Annotation> qualifiedAnno = annotation.annotationType().getAnnotation(
    Class.forName("javax.inject.Qualified", false, annoLoader));
```
This is more or less what Weld does (mind you through tons and tons of indirection).

**Comment by rotty3000** [comment] 2018-12-20 17:51
However I'm trying one more test just to make sure I have a whole picture.

**Comment by rotty3000** [comment] 2018-12-20 18:22
I did a followup check because `@Service` may not have been an exemplary case. You might consider that it is "well known" to the CDI container setup. And so there may have been favour around it's classloading.

In order to eliminate that potential case I created a separate bundle which only contains a qualifier annotation (`@FooQ`). Now this bundle DOES import the `javax.inject` package. However when the client code uses `@FooQ`, does not import the `javax.inject` Weld still properly identifies that the qualifer `@FooQ` was used and everything works as expected. So well-known-ness is not an issue either.

**Comment by bjhargrave** [comment] 2018-12-20 18:36
Nice research @rotty3000. So I think any issue with Sisu/Guice is that the annotation processing code therein does not properly handle class loading of annotations when processing an annotation chain. It likely assumes (incorrectly in modular runtime environments) that all annotations in the processing chain are visible from the application classes class loader.

You should file a bug against Sisu. In the interim, you could work around this by manually importing javax.inject in your bundles (to handle the Qualifier case).

**Comment by bjhargrave** [comment] 2018-12-20 18:37
I think we can close this issue based upon the research done and conclusions reached as a result.

**Closed by bjhargrave** 2018-12-20 18:37 UTC
