### ISSUE TITLE
Launcher does not clean up temporary files and directories properly

### ISSUE THREAD

**Issue by tobias--** [bndtools/bnd#2308] opened 2018-02-12 16:18 UTC
I noticed that using the bnd launcher, temporary jars and folders created by EmbeddedLauncher.java and Launcher.java are not being deleted. I am not sure whether the shutdown hooks are not being executed at all or whether the file handles are still open (see also #526). I noticed that the IO utility used for deleting folders swallows exception and the launcher does not log inside the shutdown hook, so there is no obvious to tell whether the shutdown hook is never executed or just fails to delete the files and folders. Either way, this behavior fills up disk space quickly.

createTempFile in EmbeddedLauncher.java: https://github.com/bndtools/bnd/blob/e041e0a058655c733d4d9c7dc3d9161078d92040/biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java#L56

createTempFile in Launcher.java: https://github.com/bndtools/bnd/blob/e041e0a058655c733d4d9c7dc3d9161078d92040/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L906

Swallowed IOException: https://github.com/bndtools/bnd/blob/e041e0a058655c733d4d9c7dc3d9161078d92040/aQute.libg/src/aQute/lib/io/IO.java#L655

I am experiencing this issue on Windows machines with java 1.8.0_161 and bndtools 3.5.0. Shutdown hooks of installed bundles do get called properly. Any ideas on what could be the cause?

**Comment by bjhargrave** [comment] 2018-02-12 16:26
Windows file system is probably the cause. It wont allow open files to be deleted. And it is likely that these files are still open during shutdown. For example all of the temp files created by the embedded launcher are in a URLClassLoader used to run the launcher.

**Comment by tobias--** [comment] 2018-02-15 14:37
So what are my options? Define the storage dir and delete this directory in a separate process? I'd prefer to have either the framework or the launcher cleanup after themselves

**Comment by bjhargrave** [comment] 2018-02-15 14:51
Well the launcher and the framework are trying to clean up. However, if the JVM keeps the files open and the Windows file system prevents the files from being deleted, what else can be done?

**Comment by bjhargrave** [comment] 2018-02-15 15:05
The EmbeddedLauncher closes the URLClassLoader would should close the underlying files and allow them to be deleted. However, this wont happen generally

https://github.com/bndtools/bnd/blob/93b087d771b3dbfdecc2f965152b036d5c944ead/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L327-L339

since generally System.exit is used to terminate the VM.

**Comment by bjhargrave** [comment] 2018-02-15 15:23
Since almost all code path result in System.exit being called, the files are still opened when the VM exits and cannot be deleted on Windows. This code would need a large rewrite to avoid calling System.exit until after all the files are (hopefully) closed.

**Comment by tobias--** [comment] 2018-02-15 15:43
This must be it. I was not aware that System.exit messes with try-with-resources.

**Comment by bjhargrave** [comment] 2018-02-15 15:47
It doesn't mess with them per se. But since control flow doesn't return back to complete the try block, since System.exit terminates the VM abruptly, the close logic never runs.

**Comment by pkriens** [comment] 2019-02-01 13:35
I also do not see a good solution. The shell script that starts the launcher runs in another process and could clean up. I think that is the best solution.

I am closing this issue, feel free to reopen it if you have ideas how to attack this inside the launcher.

**Closed by pkriens** 2019-02-01 13:35 UTC
