### ISSUE TITLE
scr annotation error reporting crashes in 6.4.0

### ISSUE THREAD

**Issue by sheenobu** [bndtools/bnd#5463] opened 2022-12-08 00:47 UTC
In Bndtools 6.3.1, incorrect SCR annotation usage will show descriptive errors. 

In Bndtools 6.4.0, the same code causes very unclear errors. 

Version details:

Eclipse:
```
Version: 2022-09 (4.25.0)

Build id: 20220908-1902
```

Bndtools:
```
Bndtools https://bndtools.org/	bndtools.core	6.4.0.REL-202211291949-g25e4898	bndtools.main.feature
```

What you see on build in 6.4.0

<img width="404" alt="Screen Shot 2022-12-07 at 4 32 04 PM" src="https://user-images.githubusercontent.com/1443459/206326944-aceaaf38-ab47-45e4-a7ca-b3df4880590c.png">

Error text in 6.4.0:

```
class aQute.bnd.component.error.DeclarativeServicesAnnotationError 
cannot be cast to class aQute.bnd.component.error.DeclarativeServicesAnnotationError
(aQute.bnd.component.error.DeclarativeServicesAnnotationError 
is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4ad8d36f; 
aQute.bnd.component.error.DeclarativeServicesAnnotationError 
is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5f2788f2)
```

What you see on build in 6.3.1:

<img width="631" alt="Screen Shot 2022-12-07 at 4 45 15 PM" src="https://user-images.githubusercontent.com/1443459/206328607-7489be12-b398-474e-b761-3c5bc2e3bd2e.png">

Error text in 6.3.1:

```
Description	Resource	Path	Location	Type
[....activate(Ljava/util/Dictionary;)V] Non annotation type for activation object with descriptor (Ljava/util/Dictionary;)V, type java/util/Dictionary	...	...	Unknown	Bndtools Problem Marker
```

**Comment by bjhargrave** [comment] 2022-12-08 14:52
The error text implies there are 2 versions of the bndlib plugin installed in your eclipse. Please install a new, fresh eclipse and bndtools 6.4.0 and see if you still have this problem.

If you open a host console in your eclipse installation, you should only see one version of each bnd plugin.

```
g! lb bnd
START LEVEL 6
   ID|State      |Level|Name
 2212|Resolved   |    1|biz.aQute.bnd.embedded-repo (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2213|Resolved   |    4|biz.aQute.bnd.maven (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2214|Resolved   |    4|biz.aQute.bnd.util (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2215|Resolved   |    4|biz.aQute.bndlib (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2218|Resolved   |    4|bndtools.api (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2219|Active     |    4|bndtools.builder (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2220|Active     |    4|bndtools.core (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2221|Active     |    4|bndtools.core.services (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2222|Active     |    4|bndtools.jareditor (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2223|Active     |    4|bndtools.m2e (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2224|Starting   |    4|bndtools.release (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2225|Active     |    4|org.bndtools.headless.build.manager (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2226|Active     |    4|org.bndtools.headless.build.plugin.ant (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2227|Active     |    4|org.bndtools.headless.build.plugin.gradle (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2228|Starting   |    4|org.bndtools.launch (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2229|Starting   |    4|org.bndtools.remoteinstall (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2230|Starting   |    4|org.bndtools.templating (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2231|Starting   |    4|org.bndtools.templating.gitrepo (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2232|Active     |    4|org.bndtools.versioncontrol.ignores.manager (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
 2233|Active     |    4|org.bndtools.versioncontrol.ignores.plugin.git (6.4.0.202211161944-RC3)|6.4.0.202211161944-RC3
```

**Comment by sheenobu** [comment] 2022-12-08 19:34
Did lots of experimentation and it looks like oomph eclipse installer is setting up my stock eclipse install with bnd.util and bndlib 6.3.x before I even launch eclipse. This is specific to "Eclipse IDE for Enterprise Java and Web Developers". If I missed a guide somewhere telling me not to use that eclipse install, then egg on my face.

Removed the following folders+folders:

 * $HOME/.eclipse
 * $HOME/.p2
 * $HOME/Library/Preferences/org.eclipse.*
 * $HOME/Library/Saved Application State/org.eclipse.*
 
Updated oomph eclipse installer.

Installed eclipse 2022-12 "Eclipse IDE for Enterprise Java and Web Developers" via the oomph eclipse installer. About 70% of the way in the installation .p2/pool gets bndlib 6.3.x

$HOME/eclipse/jee-latest-released/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.oomph.setup shows:

```
[2022-12-08 11:18:17] Downloading biz.aQute.bndlib
[2022-12-08 11:18:18] Fetching biz.aQute.bndlib_6.3.1.202206071316.jar from https://mirrors.xmission.com/eclipse/releases/2022-12/202212071000/plugins/ (3.04MB)
[2022-12-08 11:18:39] Downloading biz.aQute.bnd.util
[2022-12-08 11:18:39] Fetching biz.aQute.bnd.util_6.3.1.202206071316.jar from https://mirrors.xmission.com/eclipse/releases/2022-12/202212071000/plugins/ (414.52kB)
[2022-12-08 11:20:06] Installing biz.aQute.bnd.util [6.3.1.202206071316]
[2022-12-08 11:20:06] Installing biz.aQute.bndlib [6.3.1.202206071316]
```

Boot eclipse, check OSGi host console:

```
g! lb bnd
START LEVEL 6
   ID|State      |Level|Name
    5|Resolved   |    4|biz.aQute.bnd.util (6.3.1.202206071316)|6.3.1.202206071316
    6|Resolved   |    4|biz.aQute.bndlib (6.3.1.202206071316)|6.3.1.202206071316
```

Install Bndtools 6.4.0.REL from marketplace, restart, check OSGI Host console again:

```
g! lb bndlib
START LEVEL 6
   ID|State      |Level|Name
    6|Resolved   |    4|biz.aQute.bndlib (6.3.1.202206071316)|6.3.1.202206071316
  914|Resolved   |    4|biz.aQute.bndlib (6.4.0.202211291949)|6.4.0.202211291949

g! lb bnd.util
START LEVEL 6
   ID|State      |Level|Name
    5|Resolved   |    4|biz.aQute.bnd.util (6.3.1.202206071316)|6.3.1.202206071316
  913|Resolved   |    4|biz.aQute.bnd.util (6.4.0.202211291949)|6.4.0.202211291949
```

All I can track it to is simpleconfigator. I didn't check it before but after it ends up with both:

```
W49 2 configuration % grep bndlib org.eclipse.equinox.simpleconfigurator/bundles.info
biz.aQute.bndlib,6.4.0.202211291949,file:/Users/sheena/.p2/pool/plugins/biz.aQute.bndlib_6.4.0.202211291949.jar,4,false
biz.aQute.bndlib,6.3.1.202206071316,file:/Users/sheena/.p2/pool/plugins/biz.aQute.bndlib_6.3.1.202206071316.jar,4,false
```

removing the two 6.3.x references in this file fixes the issue.

**Comment by bjhargrave** [comment] 2022-12-08 19:36
It may be that Eclipse m2e is dragging in bndlib. I seem to recall that m2e 2.x now uses bndlib. @laeubi

**Comment by laeubi** [comment] 2022-12-08 19:44
m2e uses BND since 1.17 or even longer I think. but with proper imports there shouldn't be an issue at all?

**Comment by bjhargrave** [comment] 2022-12-09 16:34
So I don't think there is a bnd problem here. It seems to be an installation issue. So I think we can close this issue.

**Comment by laeubi** [comment] 2022-12-09 16:35
@sheenobu is there a stacktrace so one can see where the error originates from?

**Comment by sheenobu** [comment] 2022-12-10 18:47
This was all I could find (redacted the project name):


```
Errors occurred while calling bndCall after actions
Unexpected exception in bndCall after action: Decorating P/${projectName}
class aQute.bnd.component.error.DeclarativeServicesAnnotationError cannot be cast to class aQute.bnd.component.error.DeclarativeServicesAnnotationError (aQute.bnd.component.error.DeclarativeServicesAnnotationError is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1cb44a2f; aQute.bnd.component.error.DeclarativeServicesAnnotationError is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5b1295c0)
```

**Comment by sheenobu** [comment] 2022-12-10 18:49
Found it
```
org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:326)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.runtime.CoreException: Errors occurred while calling bndCall after actions
	at bndtools.central.Central.bndCall(Central.java:746)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:168)
	... 13 more
```

**Comment by juergen-albert** [comment] 2023-01-06 16:23
The issue is a bit strange. @sheenobu can execute the command `inspect cap osgi.wiring.package biz.aQute.bndlib` in your console and post the result?

**Comment by pkriens** [comment] 2023-02-20 17:01
@sheenobu Still an issue?

**Comment by pkriens** [comment] 2023-02-23 11:14
Closing for no reaction

**Closed by pkriens** 2023-02-23 11:14 UTC
Labels: waiting

**Comment by laeubi** [comment] 2023-02-27 06:14
I think the main problem is this line:

https://github.com/bndtools/bnd/blob/8ab7b919cc0c4eee0a7d6f05b06327b5e81f74d7/bndtools.builder/src/org/bndtools/builder/handlers/component/DSAnnotationErrorHandler.java#L25

as it simply cast the object without an `intanceof` check there is actually not guarantee that the item is of the desired type nor that it is a compatible type. So if the producer of that error is exposed to a different package version of bndlib, then you will see exactly this error.

**Comment by pkriens** [comment] 2023-02-27 11:00
You could be right. However, then there is another problem since the DSAnnotationErrorHandler should be linke to error location of the given type.

**Comment by laeubi** [comment] 2023-02-27 11:24
Depends on how you define "problem", obviously there is no direct dependency between producer+consumer otherwise OSGi would have wired a constant class-space and you won't see the problem. So casting Objects because you are sure it is type X *might* be considered a programming problem/error, at least it is error prone.

If it is a deployment "problem" (e.g. multiple version of Bndtools, a provider that produces problems that are unexpected (maven?)) or a leakage from one context of another is something that I can't tell from the code and provided information :-)

**Comment by pkriens** [comment] 2023-02-27 11:37
This is designed by Eclipse to link an extension to an error type. If you install 2 bndlibs in Eclipse this stuff will get you lots of fun errors. This code is irrelevant outside Eclipse workbench. So this is a symptom of a wrong setup somehow.

Since the original reporter is not responding I am not sure what we're still doing here?

**Comment by pkriens** [comment] 2023-02-27 13:29
> Well it was asked why this "strang error" can even happen and I showed you why and how this could happen, if you think it helps the user to throw random error dialogs the user has no clue, keep it.

Well, the source of this error is likely something much bigger than a cast because the API we use guarantees the matching types. _Therefore, the cast exception is actually good, it is a true exception and should not  happen_! It tells us something bigger is wrong. In a correctly setup Eclipse it is impossible. So fixing the cast would likely be like taking an aspirin against an ulcer, you muffle away the symptom but you're making it harder to diagnose the root cause. 

Time is limited so I have to pick my fights, this just doesn't seem important, as is further evidenced by the absence of the reporter in this discussion.

**Comment by laeubi** [comment] 2023-02-27 14:11
> because the API we use guarantees the matching types

Obviously not ;-)

> Therefore, the cast exception is actually good, it is a true exception and should not happen! It tells us something bigger is wrong. In a correctly setup Eclipse it is impossible. So fixing the cast would likely be like taking an aspirin against an ulcer, you muffle away the symptom but you're making it harder to diagnose the root cause.

![](https://external-preview.redd.it/jzgQ7j1IbVeJRaDU-A6GPetca7wmoHrdH_wIn1PKEPQ.png?auto=webp&v=enabled&s=0959566f8c36d9f84859f614e5e332bb67db0ba3)
