### ISSUE TITLE
NoClassDefFoundError in PkgRenameParticipant

### ISSUE THREAD

**Issue by psoreide** [bndtools/bnd#5942] opened 2023-12-20 01:45 UTC
* Eclipse Version: 2023-06 (4.28.0)
* Bndtools: 7.0.0
---
When renaming a package (with update references checked) I get:
```
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/corext/refactoring/rename/RenamePackageProcessor
	at bndtools.refactor.PkgRenameParticipant.initialize(PkgRenameParticipant.java:69)
	at org.eclipse.ltk.core.refactoring.participants.RefactoringParticipant.initialize(RefactoringParticipant.java:108)
        ...
```
It seems the internal eclipse class has moved.

**Comment by kriegfrj** [comment] 2023-12-20 02:01
Thanks @psoreide, this looks like a duplicate of #5891, which @chrisrueger fixed in #5892. It is available in HEAD and should be available in the next release.

If you think you have found something different, let us know and we'll re-open this. Thanks!

**Closed by kriegfrj** 2023-12-20 02:01 UTC
