### ISSUE TITLE
Discussion about Eclipse PDE's usage of biz.aQute.bndlib and possible future problems

### ISSUE THREAD

**Issue by tjwatson** [bndtools/bnd#5788] opened 2023-09-28 19:06 UTC
See https://github.com/eclipse-pde/eclipse.pde/discussions/774

While working on some BND PRs and trying them out on the latest Eclipse I-Builds I noticed that I would end up with two versions of `biz.aQute.bndlib` installed.  This causes loads of conflict resolutions to be worked out by the bundle resolver.  When BND tools 7 gets released, users are going to notice a significant pause when they restart after installing or updating BND tools 7.  Using `-clean` option to start Eclipse works around this because it allows the resolver to give precedence to the higher versioned bundle.

If PDE continues with its usage of `biz.aQute.bndlib` as a bundle, instead of embedding it like I suggest, then we may want to add something about starting with -clean to the release notes for BND Tools 7 release.

**Comment by pkriens** [comment] 2023-09-29 13:06
Looks awkward?

This is caused by Eclipse including bndlib? Should we have a meeting to see if we can resolve this somehow? 

I do sympathize with the embedding. It is easy to do and it totally solves the problem. Libraries should not be shared, only properly API'd code with interfaces should ever be shared.

**Comment by juergen-albert** [comment] 2023-09-29 13:21
I believe this found its way into eclipse with the automatic manifest generation feature @laeubi integrated. It uses the bnd lib underneath.

**Comment by tjwatson** [comment] 2023-09-29 13:27
I want to be clear.  This does not necessarily cause an unresolveable conflict.  It just complicates the ability for the Felix bundle resolver to find the correct solution.  Luckily, once a solution is found then it is cached and all restarts are quick.

For now, I think the best approach is to have the Eclipse platform update their version of `biz.aQute.bndlib` each time BND tools has a release.

**Comment by tjwatson** [comment] 2023-09-29 13:38
I think one complication is the fact that `biz.aQute.bndlib` exports AND imports some of its own packages (but not all):

```
    aQute.bnd.annotation; version="2.0.0" <biz.aQute.bndlib_6.4.1.202306080939 [478]>
    aQute.bnd.annotation.headers; version="2.0.0" <biz.aQute.bndlib_6.4.1.202306080939 [478]>
    aQute.bnd.annotation.metatype; version="1.45.0" <biz.aQute.bndlib_6.4.1.202306080939 [478]>
    aQute.bnd.annotation.plugin; version="1.1.0" <biz.aQute.bndlib_6.4.1.202306080939 [478]>
    aQute.bnd.annotation.xml; version="1.1.0" <biz.aQute.bndlib_6.4.1.202306080939 [478]>
```

It is not clear to me why the library substitutes this subset of packages, but not others. This is showing what my biz.aQute.bndlib_7.1.0.202309281339-SNAPSHOT build is wired to when I install it into the latest I-Build of Eclipse.  So they get substituted for the content from the old bundle.  They get substituted because the resolver is obligated to try and wire requirements to capabilities from providers that are already resolved in an effort to reduce the number of providers with substitutions.  But with all the uses declared this leaves the resolver bouncing things around until it gets everything figured out.

I have not confirmed the substituted packages cause the slowdown, it is just a suspicion.

**Comment by laeubi** [comment] 2023-09-29 14:18
> Libraries should not be shared, only properly API'd code with interfaces should ever be shared.

Can you reference the section in the OSGi spec that suggest this approach? How would two bundles than share code that both uses BNDlib if they come from different classlaoders?

**Comment by laeubi** [comment] 2023-09-29 14:27
> It is not clear to me why the library substitutes this subset of packages, but not others.

AFAIK bnd is "smart" here to see if your bundle only *exports* a "true" API (== no substitution) or if you bundle contains some implementation for it (== substitution).

Because of this bit surprising behavior and I think substituation is only useful for some very rare use-cases (e.g. you embedd a third party API) I usually disable the feature all together.

**Comment by bjhargrave** [comment] 2023-09-29 14:28
> For now, I think the best approach is to have the Eclipse platform update their version of `biz.aQute.bndlib` each time BND tools has a release.

+1

**Comment by pkriens** [comment] 2023-10-12 07:34
@tjwatson @bjhargrave can we close this issue as nothing to do?

**Closed** 2023-10-12 11:53 UTC
