### ISSUE TITLE
bndrun implicit repo, repos of maven dependencies not considered

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3361] opened 2019-07-29 18:44 UTC
If a Maven project is using the bnd-run-maven-plugin the dependencies of that project are used to fill up an implicit repository.

If the project adds further Maven repositories in its pom file using `repository` elements in the `<repositories>...</repositories>` part, that repositories are used to lookup for depend artifacts.

AFAIK on a "normal" Maven build of a JAR module the repositories of a dependency are used to resolve / fetch the dependencies of that dependency.

For me it seems that Bnd does not use the repositories of dependencies to fetch a dependent of a dependency.

See e.g. the two comments
* https://github.com/openhab/openhab-distro/issues/927#issuecomment-516064356
* https://github.com/openhab/openhab-distro/issues/927#issuecomment-516079166

**Comment by cdjackson** [comment] 2019-10-13 15:20
Hi @maggu2810 yes, this is also the same issue that I'm seeing.

**Comment by rotty3000** [comment] 2019-10-13 16:46
in the short term the solution is to bind the resolve execution to package phase, this should not have a major impact on build performance

**Comment by rotty3000** [comment] 2019-10-13 16:48
the problem is that in m2e there doesn't seem to be a convenient way to get the execution configuration for a task without it being in the current phase.

I am strongly resisting the path of parsing the xml config.. but we may not have a choice. Any help here would be appreciated.

**Comment by rotty3000** [comment] 2019-12-15 00:00
@maggu2810 @cdjackson is still an issue? The issue over on OpenHAB is really huge. Are there simple steps to reproduce? I've never seen this issue myself and have worked on several projects using bndtools.m2e that use many different maven repositories.

**Comment by rotty3000** [comment] 2019-12-15 00:02
I should add, I'd like to help resolve this issue for you guys particularly because we'd like to release bnd 5.0.0 early new year and it would be great if OpenHAB had major issues resolved in that release. Please let me know.

**Comment by rotty3000** [comment] 2019-12-15 00:05
Something I would suggest! Perhaps try removing the explicit use of `bnd-indexer-maven-plugin`. This should not be needed during the normal development lifecycle of projects unless for explicit release of R5 repositories (which are cool, but no longer explicitly required since bnd-*-maven-plugins can rely on maven dependencies natively.)

Take a look at the recent docs for the maven plugins, particularly the part about [`includeDependencyManagement`](https://github.com/bndtools/bnd/tree/master/maven/bnd-resolver-maven-plugin#configuration-properties)

**Comment by rotty3000** [comment] 2019-12-15 04:17
I don't think this is a _bug_ per say. It's really more of a limitation of resolving against explicit indexes. When doing so you need to update the indexer to account these new repositories which is not something your average maven user knows how to do.

W.r.t OpenHAB specifically, I've made a PR which demonstrates how to make the change from explicit to implicit indexes here https://github.com/openhab/openhab-core/pull/1274

**Comment by maggu2810** [comment] 2019-12-15 08:54
Hm, perhaps you get my explanation in the first comment of this issue wrong.

The report has nothing to do with the `bnd-indexer-maven-plugin` but about the implicit repo creation only.

I can try to create a simple reproducable demo if the problem still exists.

**Comment by maggu2810** [comment] 2019-12-15 09:23
To get you a short summary that makes it perhaps more visible (I assume we could mix the naming "artifact" and "bundle" here as in this issue it is all about "bundles" created by the Maven plugins and so by Maven artifacts):

* there is an artifact A that is deployed to repository REPO_A only
* there is an artifact B that depends on artifact A (scope compile) and so its POM file added REPO_A to its repository section
* there is an artifact APP that is using the "bnd-run-maven-plugin"
* the APP depends (let's say scope "compile") on artifact B
* because of the dependency chain APP depends on A (transitive)
* because APP depends on B Maven also considers the repositories defined by B (REPO_A) for dependency resolution
* it seems (at the time I created the issue) if we open the bndrun file of APP inside the Eclipse IDE and try to resolve it, the repository REPO_A is not used and A cannot be found by Bnd.

**Comment by rotty3000** [comment] 2019-12-15 15:21
If that is the case, it's a maven issue, because the implicit repo asks maven to resolve all dependencies.

**Comment by maggu2810** [comment] 2019-12-15 17:19
# Demo

See sources can be found here: https://github.com/maggu2810/bnd-app-repo

All artifacts are using the group ID `tmp.bnd-app-repo`.

I used a Linux system, so `~` and `/tmp/` will be available.

Change the pathes if you are using it on another OS.

## All in one repo (the local one)

Ensure the local Maven repo does not contain any of the bundles:

```
rm -rf ~/.m2/repository/tmp/bnd-app-repo/
```

Build both bundles and ensure they are deployed to the local Maven repo

```
cd bundle1
mvn clean install
cd ..

cd bundle2
mvn clean install
cd ..
```

Now build and resolve the app.

```
cd app
mvn clean install bnd-resolver:resolve
cd ..
```

All fine

## Bundle 1 in another repository

Ensure the local Maven repo does not contain any of the bundles:

```
rm -rf ~/.m2/repository/tmp/bnd-app-repo/
```

Build bundle1 and deploy it to a temporary repository at `/tmp/repo-bundle1`

```
cd bundle1
mvn clean package deploy:deploy -DaltDeploymentRepository=tmp::default::file:///tmp/repo-bundle1
cd ..
```

The `bundle2` already consider the repository at `/tmp/repo-bundle1` (see POM).

Build bundle2

```
cd bundle2
mvn clean install
cd ..
```

All fine, bundle2 is able to find bundle1

Now build and resolve the app.

```
cd app
mvn clean install bnd-resolver:resolve
cd ..
```

I don't think it is a defect of Maven itself.

To demonstrate I added a "bundle3" that depends on "bundle2" but uses stuff from "bundle1".
Also "bundle3" does not contain the repository declaration to find bundle1.

```
cd bundle3
mvn clean install
cd ..
```

**Comment by maggu2810** [comment] 2019-12-15 17:20
Please have a look at the demo above.

The `maven-compiler-plugin` can handle the situation (it can build bundle3), the `bnd-resolver-maven-plugin` cannot handle it (as it is not able to resolve the app).

**Comment by maggu2810** [comment] 2019-12-15 17:21
Would it be possible to open this issue again until some explanation is given?

**Comment by rotty3000** [comment] 2019-12-15 17:37
I will investigate today.

**Comment by rotty3000** [comment] 2019-12-16 18:09
You're right. I have a fix coming.

**Comment by rotty3000** [comment] 2019-12-16 18:22
Thanks for the example project, that helped a lot!

**Closed** 2019-12-17 15:17 UTC

**Comment by maggu2810** [comment] 2019-12-17 15:23
Thanks for having a look at and fixing it.
