### ISSUE TITLE
NPE while building workspace

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4140] opened 2020-06-05 12:24 UTC
The problem as mentioned in https://github.com/bndtools/bnd/issues/4085 still exists. On clicking the refresh icon results in NPE.

```
eclipse.buildId=4.15.0.I20200305-0155
java.version=1.8.0_241
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -keyring /Users/amit/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/Users/amit/sandbox-luther/ -product org.eclipse.epp.package.java.product -keyring /Users/amit/.eclipse_keyring

org.eclipse.core.jobs
Error
Fri Jun 05 14:23:47 CEST 2020
An internal error occurred during: "Reload".

java.lang.NullPointerException
	at bndtools.explorer.BndtoolsExplorer$3.lambda$run$1(BndtoolsExplorer.java:375)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Bndtools Version:   `5.2.0.DEV-202006041756-gebdb6c7`

**Comment by bjhargrave** [comment] 2020-06-05 12:30
Yes, I had not fixed it correctly in my original fix. But I fixed the fix in 

https://github.com/bndtools/bnd/commit/194abddba8ee07bfaddceee3bb9a253217df7f87#diff-170b5b66981b7e41c09ebaa58c7b5842L371-R370

I am unable to reproduce it any longer on the osgi-test repo. 

So if you still find it exists on the latest 5.2.0.DEV builds, I will need a repo which reproduced the problem so that I can debug.

**Comment by bjhargrave** [comment] 2020-06-05 12:36
One way I could see that the NPE is possible is that you are using a Bnd Workspace in Bndtools but have NOT created a `cnf` project in Eclipse. That is, there is a cnf folder on the disk but you have not imported it as `cnf` project in Eclipse (or have it closed in Eclipse).

**Comment by amitjoy** [comment] 2020-06-05 13:02
@bjhargrave I noticed this log - `Cannot find workspace location for bnd configuration file /Users/amit/project/repos/ff/com.amitinside.project/cnf/build.bnd`. It's very strange that `cnf` has been imported and open in Eclipse Workspace.

**Comment by bjhargrave** [comment] 2020-06-05 13:28
Sounds like something is wrong in your workspace. If you can make it available as a small github repo, I can debug.

**Comment by amitjoy** [comment] 2020-06-08 08:09
As an example, you can use this repo https://github.com/amitjoy/feature-flags-for-osgi

For you reference, I am currently using 5.2.0.DEV-202006051916-gcff3f92

**Comment by bjhargrave** [comment] 2020-06-08 13:30
The issue here stems from the fact that you have Eclipse projects for both cnf and the root of the repo. So cnf/build.bnd can be found in 2 ways:

`[L/cnf/build.bnd, L/com.amitinside.featureflags.parent/cnf/build.bnd]`

Bndtools handled this poorly. I will fix.

**Closed** 2020-06-08 14:25 UTC
